package models

// type Farmer struct {
// 	ID                        primitive.ObjectID  `json:"id" form:"id," bson:"_id,omitempty"`
// 	AlternateNumber           string              `json:"alternateNumber" bson:"alternateNumber"`
// 	AadhaarNumber             string              `json:"aadhaarNumber" bson:"aadhaarNumber"`
// 	Education                 string              `json:"education" bson:"education"`
// 	FatherName                string              `json:"fatherName" bson:"fatherName"`
// 	CurrentLiveStocks         []CurrentLiveStocks `json:"currentLiveStocks" bson:"currentLiveStocks"`
// 	CurrentCrops              []CurrentCrops      `json:"currentCrops" bson:"currentCrops"`
// 	CultivationPractice       string              `json:"cultivationPractice" bson:"cultivationPractice"`
// 	Name                      string              `json:"name" bson:"name"`
// 	Gender                    string              `json:"gender" bson:"gender"`
// 	DateOfBirth               *time.Time          `json:"dateOfBirth" bson:"dateOfBirth"`
// 	Status                    string              `json:"status" bson:"status"`
// 	District                  primitive.ObjectID  `json:"district"  bson:"district,omitempty"`
// 	GramPanchayat             primitive.ObjectID  `json:"gramPanchayat"  bson:"gramPanchayat,omitempty"`
// 	IsMemberInvolvedInCbo     bool                `json:"isMemberInvolvedInCbo" bson:"isMemberInvolvedInCbo"`
// 	ActiveStatus              bool                `json:"activeStatus" bson:"activeStatus"`
// 	IsSMS                     bool                `json:"isSMS" bson:"isSMS"`
// 	FeminineMobile            bool                `json:"feminineMobile" bson:"feminineMobile"`
// 	CreditAvailed             bool                `json:"creditAvailed" bson:"creditAvailed"`
// 	HasKitchenGarden          bool                `json:"hasKitchenGarden" bson:"hasKitchenGarden"`
// 	LikeToReceiveSMS          bool                `json:"likeToReceiveSMS" bson:"likeToReceiveSMS"`
// 	LikeToReceiveVoicecall    bool                `json:"likeToReceiveVoicecall" bson:"likeToReceiveVoicecall"`
// 	HasCredits                bool                `json:"hasCredits" bson:"hasCredits"`
// 	MemberOfMGNREGNA          bool                `json:"memberOfMGNREGNA" bson:"memberOfMGNREGNA"`
// 	IsPhysicallyDisabled      bool                `json:"isPhysicallyDisabled" bson:"isPhysicallyDisabled"`
// 	IsAnyMmemberOfFamilyInCBO bool                `json:"isAnyMmemberOfFamilyInCBO" bson:"isAnyMmemberOfFamilyInCBO"`
// 	Created                   Created             `json:"createdOn" bson:"createdOn"`
// 	CreatedBy                 primitive.ObjectID  `json:"createdBy" bson:"createdBy"`
// 	Version                   int                 `json:"version"  bson:"version"`
// 	IsVoiceSMS                bool                `json:"isVoiceSMS" bson:"isVoiceSMS"`
// 	KitchenGarden             bool                `json:"kitchenGarden" bson:"kitchenGarden"`
// 	LeasedInIrrigated         float64             `json:"leasedInIrrigated"  bson:"leasedInIrrigated"`
// 	LeasedInRainfed           float64             `json:"leasedInRainfed"  bson:"leasedInRainfed"`
// 	LeasedOutIrrigated        float64             `json:"leasedOutIrrigated"  bson:"leasedOutIrrigated"`
// 	LeasedOutRainfed          float64             `json:"leasedOutRainfed"  bson:"leasedOutRainfed"`
// 	MembershipInMgnrega       bool                `json:"membershipInMgnrega" bson:"membershipInMgnrega"`
// 	MobileNumber              string              `json:"mobileNumber"  bson:"mobileNumber"`
// 	LandLineNumber            string              `json:"landLineNumber"  bson:"landLineNumber"`
// 	OwnedIrrigated            float64             `json:"ownedIrrigated"  bson:"ownedIrrigated"`
// 	OwnedRainfed              float64             `json:"ownedRainfed"  bson:"ownedRainfed"`
// 	SoilType                  primitive.ObjectID  `json:"soilType"  bson:"soilType,omitempty"`
// 	SpouseName                string              `json:"spouseName"  bson:"spouseName"`
// 	State                     primitive.ObjectID  `json:"state"  bson:"state,omitempty"`
// 	//	TotalLand                    float64              `json:"totalLand"  bson:"totalLand"`
// 	TotalMobiles                 float64              `json:"totalMobiles"  bson:"totalMobiles"`
// 	Village                      primitive.ObjectID   `json:"village"  bson:"village,omitempty"`
// 	YearlyIncome                 string               `json:"yearlyIncome"  bson:"yearlyIncome"`
// 	FarmerOrg                    primitive.ObjectID   `json:"farmerOrg"  bson:"farmerOrg,omitempty"`
// 	FarmerID                     string               `json:"farmerID"  bson:"farmerID"`
// 	DoorNumber                   string               `json:"doorNo"  bson:"doorNo"`
// 	LandMark                     string               `json:"landMark"  bson:"landMark"`
// 	Street                       string               `json:"street"  bson:"street"`
// 	PreferredMarkets             []string             `json:"preferredMarkets"  bson:"preferredMarkets"`
// 	IsDisabled                   bool                 `json:"isDisabled"  bson:"isDisabled"`
// 	FertilizerQuantity           float64              `json:"fertilizerQuantity"  bson:"fertilizerQuantity"`
// 	RainDisasterFrom             float64              `json:"rainDisasterFrom"  bson:"rainDisasterFrom"`
// 	RainDisasterTo               float64              `json:"rainDisasterTo"  bson:"rainDisasterTo"`
// 	RainfallMedFrom              float64              `json:"rainfallMedFrom"  bson:"rainfallMedFrom"`
// 	RainfallMedTo                float64              `json:"rainfallMedTo"  bson:"rainfallMedTo"`
// 	RelativeHumidityDisasterFrom float64              `json:"relativeHumidityDisasterFrom"  bson:"relativeHumidityDisasterFrom"`
// 	SeedQuantity                 float64              `json:"seedQuantity"  bson:"seedQuantity"`
// 	TemperatureDisasterFrom      float64              `json:"temperatureDisasterFrom"  bson:"temperatureDisasterFrom"`
// 	TemperatureDisasterTo        float64              `json:"temperatureDisasterTo"  bson:"temperatureDisasterTo"`
// 	WindDirectionDisasterTo      float64              `json:"windDirectionDisasterTo"  bson:"windDirectionDisasterTo"`
// 	WindDirectionMedFrom         float64              `json:"windDirectionMedFrom"  bson:"windDirectionMedFrom"`
// 	RelativeHumidityDisasterTo   float64              `json:"relativeHumidityDisasterTo"  bson:"relativeHumidityDisasterTo"`
// 	WindDirectionMedTo           float64              `json:"windDirectionMedTo"  bson:"windDirectionMedTo"`
// 	WindSpeedDisasterFrom        float64              `json:"windSpeedDisasterFrom"  bson:"windSpeedDisasterFrom"`
// 	WindSpeedDisasterTo          float64              `json:"windSpeedDisasterTo"  bson:"windSpeedDisasterTo"`
// 	WindSpeedMedFrom             float64              `json:"windSpeedMedFrom"  bson:"windSpeedMedFrom"`
// 	WindSpeedMedTo               float64              `json:"windSpeedMedTo"  bson:"windSpeedMedTo"`
// 	UniqueId                     int64                `json:"uniqueId"  bson:"uniqueId"`
// 	Password                     string               `json:"password"  bson:"password"`
// 	Assert                       []primitive.ObjectID `json:"assert"  bson:"assert"`
// 	Cast                         string               `json:"cast"  bson:"cast"`
// 	Isleadwomenhasmobile         bool                 `json:"isleadwomenhasmobile" bson:"isleadwomenhasmobile"`
// 	WomenMobileNumber            string               `json:"womenMobileNumber" bson:"womanMobileNumber"`
// 	CreditName                   string               `json:"creditName"  bson:"creditName"`
// 	DisabilityType               string               `json:"disabilityType"  bson:"disabilityType"`
// 	MemberName                   string               `json:"memberName"  bson:"memberName"`
// 	ProjectID                    primitive.ObjectID   `json:"-"  bson:"-"`
// 	CreatedDate                  *time.Time           `json:"createdDate"  bson:"createdDate"`
// 	Email                        string               `json:"email" bson:"email"`
// 	CultivatedArea               float64              `json:"cultivatedArea"  bson:"cultivatedArea"`
// 	VacantArea                   float64              `json:"vacantArea"  bson:"vacantArea"`
// 	TotalLand                    float64              `json:"totalLand"  bson:"totalLand"`
// 	CropCount                    float64              `json:"cropCount"  bson:"cropCount"`
// 	LiveStockCount               float64              `json:"liveStockCount"  bson:"liveStockCount"`
// 	AppRegistrationToken         string               `json:"appRegistrationToken" bson:"appRegistrationToken"`
// 	PinCode                      float64              `json:"pinCode"  bson:"pinCode"`
// 	Location                     Location             `json:"location"  bson:"location"`
// 	Block                        primitive.ObjectID   `json:"block"  bson:"block,omitempty"`
// 	UploadVersion                string               `json:"uploadVersion"  bson:"uploadVersion"`
// 	UserName                     string               `json:"userName"  bson:"userName"`
// }
