package constants

// BIRTHCERTIFICATE: ""
const (
	BIRTHCERTIFICATESTATUSACTIVE   = "Active"
	BIRTHCERTIFICATESTATUSDISABLED = "Disabled"
	BIRTHCERTIFICATESTATUSDELETED  = "Deleted"
	BIRTHCERTIFICATESTATUSAPPROVED = "Approved"
	BIRTHCERTIFICATESTATUSREJECTED = "Rejected"
)

const (
	OURSERVICESTATUSACTIVE   = "Active"
	OURSERVICESTATUSDISABLED = "Disabled"
	OURSERVICESTATUSDELETED  = "Deleted"
)
