package constants

// Citizen Gravians: ""
const (
	CITIZENGRAVIANSSTATUSACTIVE    = "Active"
	CITIZENGRAVIANSSTATUSDISABLED  = "Disabled"
	CITIZENGRAVIANSSTATUSDELETED   = "Deleted"
	CITIZENGRAVIANSSTATUSINIT      = "Init"
	CITIZENGRAVIANSSTATUSCOMPLETED = "Completed"
	CITIZENGRAVIANSSTATUSREJECTED  = "Rejected"
	// CITIZENGRAVIANSSTATUSREJECTED  = "Closed"
)
