package constants

// Citizen Gravians: ""
const (
	CITIZENGRAVIANSLOGSTATUSACTIVE    = "Active"
	CITIZENGRAVIANSLOGSTATUSDISABLED  = "Disabled"
	CITIZENGRAVIANSLOGSTATUSDELETED   = "Deleted"
	CITIZENGRAVIANSLOGSTATUSINIT      = "Init"
	CITIZENGRAVIANSLOGSTATUSCOMPLETED = "Completed"
	CITIZENGRAVIANSLOGSTATUSREJECTED  = "Rejected"
)
