package constants

// Cron Logs
const (
	CRONLOGSTATUSINIT      = "Init"
	CRONLOGSTATUSACTIVE    = "Active"
	CRONLOGSTATUSDISABLED  = "Disabled"
	CRONLOGSTATUSDELETED   = "Deleted"
	CRONLOGSTATUSCOMPLETED = "Completed"
	CRONLOGSTATUSFAILED    = "Failed"
)

const (
	UPDATEPROPERTYTAXCRON         = "UPDATEPROPERTYTAXCRON"
	PROPERTYTODAYDEMANDCRON       = "PROPERTYTODAYDEMANDCRON"
	PROPERTYOVERALLDEMANDCRON     = "PROPERTYOVERALLDEMANDCRON"
	PROPERTYTODAYCOLLECTIONCRON   = "PROPERTYTODAYCOLLECTIONCRON"
	PROPERTYOVERALLCOLLECTIONCRON = "PROPERTYOVERALLCOLLECTIONCRON"
	PROPERTYMONTHDEMANDCRON       = "PROPERTYMONTHDEMANDCRON"
	PROPERTYYEARDEMANDCRON        = "PROPERTYYEARDEMANDCRON"
	PROPERTYMONTHCOLLECTIONCRON   = "PROPERTYMONTHCOLLECTIONCRON"
	PROPERTYYEARCOLLECTIONCRON    = "PROPERTYYEARCOLLECTIONCRON"
)
