package constants

//DashBoard Trade License
const (
	DASHBOARDTRADELICENSESTATUSACTIVE   = "Active"
	DASHBOARDTRADELICENSESTATUSDISABLED = "Disabled"
	DASHBOARDTRADELICENSESTATUSDELETED  = "Deleted"
)

//DashBoard Trade License Day Wise
const (
	DASHBOARDTRADELICENSEDAYWISESTATUSACTIVE   = "Active"
	DASHBOARDTRADELICENSEDAYWISESTATUSDISABLED = "Disabled"
	DASHBOARDTRADELICENSEDAYWISESTATUSDELETED  = "Deleted"
)
