package constants

//DashBoard Mobile Tower
const (
	DASHBOARDMOBILETOWERSTATUSACTIVE   = "Active"
	DASHBOARDMOBILETOWERSTATUSDISABLED = "Disabled"
	DASHBOARDMOBILETOWERSTATUSDELETED  = "Deleted"
)

//DashBoard Mobile Tower Day Wise
const (
	DASHBOARDMOBILETOWERDAYWISESTATUSACTIVE   = "Active"
	DASHBOARDMOBILETOWERDAYWISESTATUSDISABLED = "Disabled"
	DASHBOARDMOBILETOWERDAYWISESTATUSDELETED  = "Deleted"
)
