package constants

//DashBoard User Charge
const (
	DASHBOARDUSERCHARGESTATUSACTIVE   = "Active"
	DASHBOARDUSERCHARGESTATUSDISABLED = "Disabled"
	DASHBOARDUSERCHARGESTATUSDELETED  = "Deleted"
)

//DashBoard User Charge Day Wise
const (
	DASHBOARDUSERCHARGEDAYWISESTATUSACTIVE   = "Active"
	DASHBOARDUSERCHARGEDAYWISESTATUSDISABLED = "Disabled"
	DASHBOARDUSERCHARGEDAYWISESTATUSDELETED  = "Deleted"
)
