package constants

//DashBoard Property
const (
	DASHBOARDPROPERTYSTATUSACTIVE   = "Active"
	DASHBOARDPROPERTYSTATUSDISABLED = "Disabled"
	DASHBOARDPROPERTYSTATUSDELETED  = "Deleted"
)

//DashBoard Property Day Wise
const (
	DASHBOARDPROPERTYDAYWISESTATUSACTIVE   = "Active"
	DASHBOARDPROPERTYDAYWISESTATUSDISABLED = "Disabled"
	DASHBOARDPROPERTYDAYWISESTATUSDELETED  = "Deleted"
)
