package constants

//DashBoard Shop Rent
const (
	DASHBOARDSHOPRENTSTATUSACTIVE   = "Active"
	DASHBOARDSHOPRENTSTATUSDISABLED = "Disabled"
	DASHBOARDSHOPRENTSTATUSDELETED  = "Deleted"
)

//DashBoard Shop Rent Day Wise
const (
	DASHBOARDSHOPRENTDAYWISESTATUSACTIVE   = "Active"
	DASHBOARDSHOPRENTDAYWISESTATUSDISABLED = "Disabled"
	DASHBOARDSHOPRENTDAYWISESTATUSDELETED  = "Deleted"
)
