package constants

//DashBoard Lease
const (
	DASHBOARDLEASESTATUSACTIVE   = "Active"
	DASHBOARDLEASESTATUSDISABLED = "Disabled"
	DASHBOARDLEASESTATUSDELETED  = "Deleted"
)

//DashBoard Lease Day Wise
const (
	DASHBOARDLEASEDAYWISESTATUSACTIVE   = "Active"
	DASHBOARDLEASEDAYWISESTATUSDISABLED = "Disabled"
	DASHBOARDLEASEDAYWISESTATUSDELETED  = "Deleted"
)
