package constants

//DashBoard Water Bill
const (
	DASHBOARDWATERBILLSTATUSACTIVE   = "Active"
	DASHBOARDWATERBILLSTATUSDISABLED = "Disabled"
	DASHBOARDWATERBILLSTATUSDELETED  = "Deleted"
)

//DashBoard Water Bill Day Wise
const (
	DASHBOARDWATERBILLDAYWISESTATUSACTIVE   = "Active"
	DASHBOARDWATERBILLDAYWISESTATUSDISABLED = "Disabled"
	DASHBOARDWATERBILLDAYWISESTATUSDELETED  = "Deleted"
)
