package constants

//Document
const (
	DOCUMENTSTATUSACTIVE   = "Active"
	DOCUMENTSTATUSDISABLED = "Disabled"
	DOCUMENTSTATUSDELETED  = "Deleted"
)

//Property Document
const (
	PROPERTYDOCUMENTSTATUSACTIVE   = "Active"
	PROPERTYDOCUMENTSTATUSDISABLED = "Disabled"
	PROPERTYDOCUMENTSTATUSDELETED  = "Deleted"
)

//Property Required Document
const (
	PROPERTYREQUIREDDOCUMENTSTATUSACTIVE   = "Active"
	PROPERTYREQUIREDDOCUMENTSTATUSDISABLED = "Disabled"
	PROPERTYREQUIREDDOCUMENTSTATUSDELETED  = "Deleted"
)
