package constants

//Letter upload
const (
	LETTERUPLOADSTATUSACTIVE   = "Active"
	LETTERUPLOADSTATUSDISABLED = "Disabled"
	LETTERUPLOADRSTATUSDELETED = "Deleted"
)

// letter generate
const (
	LETTERGENERATESTATUSACTIVE    = "Active"
	LETTERGENERATESTATUSAPPROVED  = "Approved"
	LETTERGENERATESTATUSDISABLED  = "Disabled"
	LETTERGENERATESTATUSDELETED   = "Deleted"
	LETTERGENERATESTATUSDRAFT     = "Draft"
	LETTERGENERATESTATUSBLOCKED   = "Blocked"
	LETTERGENERATESTATUSSUBMITTED = "Pending"
)
