package constants

// Mobile Tower : ""
const (
	MOBILETOWERSTATUSACTIVE  = "Active"
	MOBILETOWERSTATUSPENDING = "Pending"
)

// Mobile Tower Year : ""
const (
	MOBILETOWERFYSTATUSACTIVE = "Active"
)

// Mobile Tower Tax : ""
const (
	MOBILETOWERTAXSTATUSACTIVE   = "Active"
	MOBILETOWERTAXSTATUSDISABLED = "Disabled"
	MOBILETOWERTAXSTATUSDELETED  = "Deleted"
)
const (
	MOBILETOWERREGISTRATIONRATEMASTERSTATUSACTIVE   = "Active"
	MOBILETOWERREGISTRATIONRATEMASTERSTATUSDISABLED = "Disabled"
	MOBILETOWERREGISTRATIONRATEMASTERSTATUSDELETED  = "Deleted"
)

// Property Mobile Tower : ""
const (
	PROPERTYMOBILETOWERSTATUSACTIVE   = "Active"
	PROPERTYMOBILETOWERSTATUSDISABLED = "Disabled"
	PROPERTYMOBILETOWERSTATUSDELETED  = "Deleted"
	PROPERTYMOBILETOWERSTATUSREJECTED = "Rejected"
)

//Mobile tower payment constants
const (
	MOBILETOWERPAYMENRSTATUSINIT        = "Init"
	MOBILETOWERPAYMENRSTATUSCOMPLETED   = "Completed"
	MOBILETOWERPAYMENRSTATUSNOTVERIFIED = "NotVerified"
	MOBILETOWERPAYMENRSTATUSPENDING     = "Pending"
	MOBILETOWERPAYMENRSTATUSREJECTED    = "Rejected"
	MOBILETOWERPAYMENRSTATUSACTIVE      = "Active"
)

// Payment Scenario
const (
	MOBILETOWERPAYMENTYEARLYPAYMENT             = "YearlyPayment"
	MOBILETOWERPAYMENTREGISTRATIONPAYMENT       = "RegistrationPayment"
	MOBILETOWERPAYMENTLEGACYREGISTRATIONPAYMENT = "LegacyRegistrationPayment"
)

// Trade License Basic Update Log
const (
	MOBILETOWERBASICUPDATELOGACTIVE   = "Active"
	MOBILETOWERBASICUPDATELOGDISABLE  = "Disabled"
	MOBILETOWERBASICUPDATELOGDELETED  = "Deleted"
	MOBILETOWERBASICUPDATELOGINIT     = "Init"
	MOBILETOWERBASICUPDATELOGACCEPTED = "Accepted"
	MOBILETOWERBASICUPDATELOGREJECTED = "Rejected"
)
