package constants

// MobileTower Registration Tax
const (
	MOBILETOWERREGISTRATIONTAXSTATUSACTIVE   = "Active"
	MOBILETOWERREGISTRATIONTAXSTATUSDISABLED = "Disabled"
	MOBILETOWERREGISTRATIONTAXSTATUSDELETED  = "Deleted"
)
