package constants

// Property Delete

const (
	MOBILETOWERDELETEREQUESTSTATUSINIT        = "Init"
	MOBILETOWERDELETEREQUESTSTATUSCOMPLETED   = "Completed"
	MOBILETOWERDELETEREQUESTSTATUSNOTVERIFIED = "NotVerified"
	MOBILETOWERDELETEREQUESTSTATUSREJECTED    = "Rejected"
)
