package constants

//Reassessment Request constants
const (
	MOBILETOWERREASSESSMENTREQUESTSTATUSINIT        = "Init"
	MOBILETOWERREASSESSMENTREQUESTSTATUSCOMPLETED   = "Completed"
	MOBILETOWERREASSESSMENTREQUESTSTATUSNOTVERIFIED = "NotVerified"
	MOBILETOWERREASSESSMENTREQUESTSTATUSPENDING     = "Pending"
	MOBILETOWERREASSESSMENTREQUESTSTATUSREJECTED    = "Rejected"
)

// Reassessment Request Update Collections
const (
	MOBILETOWERREASSESSMENTREQUESTSTATUSACTIVE   = "Active"
	MOBILETOWERREASSESSMENTREQUESTSTATUSDISABLED = "Disabled"
	MOBILETOWERREASSESSMENTREQUESTSTATUSDELETED  = "Deleted"
)
