package constants

// PROPERTYFIXEDARVLOG: ""
const (
	PROPERTYFIXEDARVLOGSTATUSACTIVE   = "Active"
	PROPERTYFIXEDARVLOGSTATUSDISABLED = "Disabled"
	PROPERTYFIXEDARVLOGSTATUSDELETED  = "Deleted"
	PROPERTYFIXEDARVLOGSTATUSAPPROVED = "Approved"
	PROPERTYFIXEDARVLOGSTATUSREJECTED = "Rejected"
)
