package constants

// Property Estimated Demand
const (
	ESTIMATEDPROPERTYDEMANDSTATUSPENDING  = "Init"
	ESTIMATEDPROPERTYDEMANDSTATUSACTIVE   = "Active"
	ESTIMATEDPROPERTYDEMANDSTATUSDISABLED = "Disabled"
	ESTIMATEDPROPERTYDEMANDSTATUSDELETED  = "Deleted"
)

// Property Estimated Floor
const (
	ESTIMATEDPROPERTYFLOORSTATUSPENDING  = "Init"
	ESTIMATEDPROPERTYFLOORSTATUSACTIVE   = "Active"
	ESTIMATEDPROPERTYFLOORSTATUSDISABLED = "Disabled"
	ESTIMATEDPROPERTYFLOORSTATUSDELETED  = "Deleted"
)
