package constants

// PROPERTYOTHERDEMAND: ""
const (
	PROPERTYOTHERDEMANDSTATUSACTIVE         = "Active"
	PROPERTYOTHERDEMANDPAYMENTSTATUSNOTPAID = "NotPaid"
	PROPERTYOTHERDEMANDPAYMENTSTATUSPAID    = "Paid"
	PROPERTYOTHERDEMANDSTATUSDISABLED       = "Disabled"
	PROPERTYOTHERDEMANDSTATUSDELETED        = "Deleted"
)

// PROPERTYOTHERDEMANDPAYMENTS: ""
const (
	PROPERTYOTHERDEMANDPAYMENTSTATUSINIT        = "Init"
	PROPERTYOTHERDEMANDPAYMENTCOMPLETED         = "Completed"
	PROPERTYOTHERDEMANDPAYMENTSTATUSNOTVERIFIED = "NotVerified"
	PROPERTYOTHERDEMANDPAYMENTSTATUSPENDING     = "Pending"
	PROPERTYOTHERDEMANDPAYMENTSTATUSREJECTED    = "Rejected"
)
