package constants

// PROPERTYFIXEDARV: ""
const (
	PROPERTYFIXEDARVSTATUSINIT     = "Init"
	PROPERTYFIXEDARVSTATUSACTIVE   = "Active"
	PROPERTYFIXEDARVSTATUSDISABLED = "Disabled"
	PROPERTYFIXEDARVSTATUSDELETED  = "Deleted"
	PROPERTYFIXEDARVSTATUSAPPROVED = "Approved"
	PROPERTYFIXEDARVSTATUSREJECTED = "Rejected"
)
