package constants

// Property Part payment : ""
const (
	PROPERTYPARTPAYMENTSTATUSACTIVE      = "Active"
	PROPERTYPARTPAYMENTSTATUSDISABLED    = "Disabled"
	PROPERTYPARTPAYMENTSTATUSDELETED     = "Deleted"
	PROPERTYPARTPAYMENTSTATUSPENDING     = "VerificationPending"
	PROPERTYPARTPAYMENTSTATUSCOMPLETED   = "Completed"
	PROPERTYPARTPAYMENTSTATUSINIT        = "Init"
	PROPERTYPARTPAYMENTSTATUSREJECTED    = "Rejected"
	PROPERTYPARTPAYMENTSTATUSNOTVERIFIED = "NotVerified"
)
