package constants

const (
	PROPERTYPAYMENTMODECHANGESTATUSPENDING   = "Init"
	PROPERTYPAYMENTMODECHANGESTATUSCOMPLETED = "Completed"
	PROPERTYPAYMENTMODECHANGESTATUSREJECTED  = "Rejected"
)

const (
	USERCHARGEPAYMENTMODECHANGESTATUSPENDING   = "Init"
	USERCHARGEPAYMENTMODECHANGESTATUSCOMPLETED = "Completed"
	USERCHARGEPAYMENTMODECHANGESTATUSREJECTED  = "Rejected"
)

const (
	TRADELICENSEPAYMENTMODECHANGESTATUSPENDING   = "Init"
	TRADELICENSEPAYMENTMODECHANGESTATUSCOMPLETED = "Completed"
	TRADELICENSEPAYMENTMODECHANGESTATUSREJECTED  = "Rejected"
)

const (
	SHOPRENTPAYMENTMODECHANGESTATUSPENDING   = "Init"
	SHOPRENTPAYMENTMODECHANGESTATUSCOMPLETED = "Completed"
	SHOPRENTPAYMENTMODECHANGESTATUSREJECTED  = "Rejected"
)
