package constants

// Property Delete

const (
	PROPERTYDELETEREQUESTSTATUSINIT        = "Init"
	PROPERTYDELETEREQUESTSTATUSCOMPLETED   = "Completed"
	PROPERTYDELETEREQUESTSTATUSNOTVERIFIED = "NotVerified"
	PROPERTYDELETEREQUESTSTATUSREJECTED    = "Rejected"
)
