package constants

// Property Mutation

const (
	PROPERTYMUTATIONREQUESTSTATUSINIT        = "Init"
	PROPERTYMUTATIONREQUESTSTATUSCOMPLETED   = "Completed"
	PROPERTYMUTATIONREQUESTSTATUSNOTVERIFIED = "NotVerified"
	PROPERTYMUTATIONREQUESTSTATUSREJECTED    = "Rejected"
)

// Muated Properties
const (
	MUTATEDPROPERTYSTATUSINIT     = "Init"
	MUTATEDPROPERTYSTATUSACTIVE   = "Active"
	MUTATEDPROPERTYSTATUSDISABLED = "Disabled"
	MUTATEDPROPERTYSTATUSDELETED  = "Deleted"
)
