package constants

// Property Wallet Log : ""
const (
	PROPERTYPAYEENAMECHANGESTATUSACTIVE   = "Active"
	PROPERTYPAYEENAMECHANGESTATUSPENDING  = "Pending"
	PROPERTYPAYEENAMECHANGESTATUSREJECTED = "Rejected"
	PROPERTYPAYEENAMECHANGESTATUSDISABLED = "Disabled"
	PROPERTYPAYEENAMECHANGESTATUSDELETED  = "Deleted"
)

const (
	USERCHARGEPAYEENAMECHANGESTATUSACTIVE   = "Active"
	USERCHARGEPAYEENAMECHANGESTATUSPENDING  = "Pending"
	USERCHARGEPAYEENAMECHANGESTATUSREJECTED = "Rejected"
	USERCHARGEPAYEENAMECHANGESTATUSDISABLED = "Disabled"
	USERCHARGEPAYEENAMECHANGESTATUSDELETED  = "Deleted"
)

const (
	TRADELICENSEPAYEENAMECHANGESTATUSACTIVE   = "Active"
	TRADELICENSEPAYEENAMECHANGESTATUSPENDING  = "Pending"
	TRADELICENSEPAYEENAMECHANGESTATUSREJECTED = "Rejected"
	TRADELICENSEPAYEENAMECHANGESTATUSDISABLED = "Disabled"
	TRADELICENSEPAYEENAMECHANGESTATUSDELETED  = "Deleted"
)

const (
	SHOPRENTPAYEENAMECHANGESTATUSACTIVE   = "Active"
	SHOPRENTPAYEENAMECHANGESTATUSPENDING  = "Pending"
	SHOPRENTPAYEENAMECHANGESTATUSREJECTED = "Rejected"
	SHOPRENTPAYEENAMECHANGESTATUSDISABLED = "Disabled"
	SHOPRENTPAYEENAMECHANGESTATUSDELETED  = "Deleted"
)
