package constants

// Overall Property Demand
const (
	OVERALLPROPERTYDEMANDSTATUSACTIVE   = "Active"
	OVERALLPROPERTYDEMANDSTATUSDISABLED = "Disabled"
	OVERALLPROPERTYDEMANDSTATUSDELETED  = "Deleted"
)
