package constants

//Reassessment Request constants
const (
	REASSESSMENTREQUESTSTATUSINIT        = "Init"
	REASSESSMENTREQUESTSTATUSCOMPLETED   = "Completed"
	REASSESSMENTREQUESTSTATUSNOTVERIFIED = "NotVerified"
	REASSESSMENTREQUESTSTATUSPENDING     = "Pending"
	REASSESSMENTREQUESTSTATUSREJECTED    = "Rejected"
)

// Reassessment Request Update Collections
const (
	REASSESSMENTREQUESTSTATUSACTIVE   = "Active"
	REASSESSMENTREQUESTSTATUSDISABLED = "Disabled"
	REASSESSMENTREQUESTSTATUSDELETED  = "Deleted"
)
