package constants

//Reassessment Request constants
const (
	SHOPRENTREASSESSMENTREQUESTSTATUSINIT        = "Init"
	SHOPRENTREASSESSMENTREQUESTSTATUSCOMPLETED   = "Completed"
	SHOPRENTREASSESSMENTREQUESTSTATUSNOTVERIFIED = "NotVerified"
	SHOPRENTREASSESSMENTREQUESTSTATUSPENDING     = "Pending"
	SHOPRENTREASSESSMENTREQUESTSTATUSREJECTED    = "Rejected"
)

// Reassessment Request Update Collections
const (
	SHOPRENTREASSESSMENTREQUESTSTATUSACTIVE   = "Active"
	SHOPRENTREASSESSMENTREQUESTSTATUSDISABLED = "Disabled"
	SHOPRENTREASSESSMENTREQUESTSTATUSDELETED  = "Deleted"
)
