package constants

//Shop Rent payment constants
const (
	SHOPRENTPAYMENTSTATUSINIT        = "Init"
	SHOPRENTPAYMENTSTATUSCOMPLETED   = "Completed"
	SHOPRENTPAYMENTSTATUSNOTVERIFIED = "NotVerified"
	SHOPRENTPAYMENTSTATUSPENDING     = "Pending"
	SHOPRENTPAYMENTSTATUSREJECTED    = "Rejected"
)

const (
	SHOPRENTPAYMENTSCENARIOLEGACY  = "LegacyPayment"
	SHOPRENTPAYMENTSCENARIOMONTHLY = "MonthlyPayment"
)
