package constants

// Property Delete

const (
	SHOPRENTDELETEREQUESTSTATUSINIT        = "Init"
	SHOPRENTDELETEREQUESTSTATUSCOMPLETED   = "Completed"
	SHOPRENTDELETEREQUESTSTATUSNOTVERIFIED = "NotVerified"
	SHOPRENTDELETEREQUESTSTATUSREJECTED    = "Rejected"
)
