package constants

// SOLIDWASTEUSERCHARGERATE: ""
const (
	SOLIDWASTEUSERCHARGERATESTATUSACTIVE   = "Active"
	SOLIDWASTEUSERCHARGERATESTATUSDISABLED = "Disabled"
	SOLIDWASTEUSERCHARGERATESTATUSDELETED  = "Deleted"
)
