package constants

// SOLIDWASTEUSERCHARGE: ""
const (
	SOLIDWASTEUSERCHARGESTATUSACTIVE   = "Active"
	SOLIDWASTEUSERCHARGESTATUSDISABLED = "Disabled"
	SOLIDWASTEUSERCHARGESTATUSDELETED  = "Deleted"
)

//Shop Rent payment constants
const (
	SOLIDWASTEUSERCHARGEPAYMENTSTATUSINIT        = "Init"
	SOLIDWASTEUSERCHARGEPAYMENTSTATUSCOMPLETED   = "Completed"
	SOLIDWASTEUSERCHARGEPAYMENTSTATUSNOTVERIFIED = "NotVerified"
	SOLIDWASTEUSERCHARGEPAYMENTSTATUSPENDING     = "Pending"
	SOLIDWASTEUSERCHARGEPAYMENTSTATUSREJECTED    = "Rejected"
)

const (
	SOLIDWASTEUSERCHARGEPAYMENTSCENARIOLEGACY  = "LegacyPayment"
	SOLIDWASTEUSERCHARGEPAYMENTSCENARIOMONTHLY = "MonthlyPayment"
)
