package constants

//Reassessment Request constants
const (
	SOLIDWASTEREASSESSMENTREQUESTSTATUSINIT        = "Init"
	SOLIDWASTEREASSESSMENTREQUESTSTATUSCOMPLETED   = "Completed"
	SOLIDWASTEREASSESSMENTREQUESTSTATUSNOTVERIFIED = "NotVerified"
	SOLIDWASTEREASSESSMENTREQUESTSTATUSPENDING     = "Pending"
	SOLIDWASTEREASSESSMENTREQUESTSTATUSREJECTED    = "Rejected"
)

// Reassessment Request Update Collections
const (
	SOLIDWASTEREASSESSMENTREQUESTSTATUSACTIVE   = "Active"
	SOLIDWASTEREASSESSMENTREQUESTSTATUSDISABLED = "Disabled"
	SOLIDWASTEREASSESSMENTREQUESTSTATUSDELETED  = "Deleted"
)
