package constants

// SOLIDWASTEUSERCHARGECATEGORY: ""
const (
	SOLIDWASTEUSERCHARGECATEGORYSTATUSACTIVE   = "Active"
	SOLIDWASTEUSERCHARGECATEGORYSTATUSDISABLED = "Disabled"
	SOLIDWASTEUSERCHARGECATEGORYSTATUSDELETED  = "Deleted"
)
