package constants

// SOLIDWASTEUSERCHARGESUBCATEGORY: ""
const (
	SOLIDWASTEUSERCHARGESUBCATEGORYSTATUSACTIVE   = "Active"
	SOLIDWASTEUSERCHARGESUBCATEGORYSTATUSDISABLED = "Disabled"
	SOLIDWASTEUSERCHARGESUBCATEGORYSTATUSDELETED  = "Deleted"
)
