package constants

// TRADELICENSECATEGORYTYPE
const (
	TRADELICENSECATEGORYTYPESTATUSACTIVE   = "Active"
	TRADELICENSECATEGORYTYPESTATUSDISABLED = "Disabled"
	TRADELICENSECATEGORYTYPESTATUSDELETED  = "Deleted"
)
