package constants

// Trade License Delete

const (
	TRADELICENSEDELETEREQUESTSTATUSINIT        = "Init"
	TRADELICENSEDELETEREQUESTSTATUSCOMPLETED   = "Completed"
	TRADELICENSEDELETEREQUESTSTATUSNOTVERIFIED = "NotVerified"
	TRADELICENSEDELETEREQUESTSTATUSREJECTED    = "Rejected"
)
