package constants

//Reassessment Request constants
const (
	TRADELICENSEREASSESSMENTREQUESTSTATUSINIT        = "Init"
	TRADELICENSEREASSESSMENTREQUESTSTATUSCOMPLETED   = "Completed"
	TRADELICENSEREASSESSMENTREQUESTSTATUSNOTVERIFIED = "NotVerified"
	TRADELICENSEREASSESSMENTREQUESTSTATUSPENDING     = "Pending"
	TRADELICENSEREASSESSMENTREQUESTSTATUSREJECTED    = "Rejected"
)

// Reassessment Request Update Collections
const (
	TRADELICENSEREASSESSMENTREQUESTSTATUSACTIVE   = "Active"
	TRADELICENSEREASSESSMENTREQUESTSTATUSDISABLED = "Disabled"
	TRADELICENSEREASSESSMENTREQUESTSTATUSDELETED  = "Deleted"
)
