package constants

// TRADELICENSE
const (
	TRADELICENSESTATUSACTIVE      = "Active"
	TRADELICENSESTATUSDISABLED    = "Disabled"
	TRADELICENSESTATUSDELETED     = "Deleted"
	TRADELICENSESTATUSREJECTED    = "Rejected"
	TRADELICENSESTATUSINIT        = "Init"
	TRADELICENSESTATUSPENDING     = "Pending"
	TRADELICENSESTATUSNOTVERIFIED = "NotVerified"
	TRADELICENSESTATUSVERIFIED    = "Verified"
	TRADELICENSESTATUSNOTAPPROVED = "NotApproved"
	TRADELICENSESTATUSAPPROVED    = "Approved"
)

// Trade License Payment
const (
	TRADELICENSEPAYMENRSTATUSINIT        = "Init"
	TRADELICENSEPAYMENRSTATUSCOMPLETED   = "Completed"
	TRADELICENSEPAYMENRSTATUSNOTVERIFIED = "NotVerified"
	TRADELICENSEPAYMENRSTATUSPENDING     = "VerificationPending"
	TRADELICENSEPAYMENRSTATUSREJECTED    = "Rejected"
)

// Trade License Basic Update Log
const (
	TRADELICENSEBASICUPDATELOGACTIVE   = "Active"
	TRADELICENSEBASICUPDATELOGDISABLE  = "Disabled"
	TRADELICENSEBASICUPDATELOGDELETED  = "Deleted"
	TRADELICENSEBASICUPDATELOGINIT     = "Init"
	TRADELICENSEBASICUPDATELOGACCEPTED = "Accepted"
	TRADELICENSEBASICUPDATELOGREJECTED = "Rejected"
)

// // Basic TradeLicense Update Collections
// const (
// 	BASICTRADELICENSEUPDATESTATUSACTIVE   = "Active"
// 	BASICTRADELICENSEUPDATESTATUSDISABLED = "Disabled"
// 	BASICTRADELICENSEUPDATESTATUSDELETED  = "Deleted"
// )
