package constants

// TRADELICENSERATEMASTER
const (
	TRADELICENSERATEMASTERSTATUSACTIVE   = "Active"
	TRADELICENSERATEMASTERSTATUSDISABLED = "Disabled"
	TRADELICENSERATEMASTERSTATUSDELETED  = "Deleted"
)
