package constants

// TRADELICENSEBUSINESSTYPE
const (
	TRADELICENSEBUSINESSTYPESTATUSACTIVE   = "Active"
	TRADELICENSEBUSINESSTYPESTATUSDISABLED = "Disabled"
	TRADELICENSEBUSINESSTYPESTATUSDELETED  = "Deleted"
)
