package constants

// USERCHARGECATEGORY : ""
const (
	USERCHARGECATEGORYSTATUSACTIVE   = "Active"
	USERCHARGECATEGORYSTATUSDISABLED = "Disabled"
	USERCHARGECATEGORYSTATUSDELETED  = "Deleted"
)

//PROPERTYUSERCHARGE
const (
	PROPERTYUSERCHARGESTATUSACTIVE   = "Active"
	PROPERTYUSERCHARGESTATUSINIT     = "Init"
	PROPERTYUSERCHARGESTATUSREJECTED = "Rejected"
	PROPERTYUSERCHARGESTATUSDISABLED = "Disabled"
	PROPERTYUSERCHARGESTATUSDELETED  = "Deleted"
)

//USERCHARGERATEMASTER
const (
	USERCHARGERATEMASTERSTATUSACTIVE   = "Active"
	USERCHARGERATEMASTERSTATUSDISABLED = "Disabled"
	USERCHARGERATEMASTERSTATUSDELETED  = "Deleted"
	USERCHARGEPAYMENTSTATUSINIT        = "Init"
	USERCHARGEPAYMENTSCENARIOMONTHLY   = "MonthlyPayment"
)

const (
	USERCHARGEUPDATELOGSTATUSACTIVE   = "Active"
	USERCHARGEUPDATELOGSTATUSDISABLED = "Disabled"
	USERCHARGEUPDATELOGSTATUSDELETED  = "Deleted"
)

const (
	USERCHARGELOGSTATUSACTIVE   = "Active"
	USERCHARGELOGSTATUSDISABLED = "Disabled"
	USERCHARGELOGSTATUSDELETED  = "Deleted"
)
