package constants

// WATERTAXARV: ""
const (
	WATERTAXARVSTATUSACTIVE   = "Active"
	WATERTAXARVSTATUSDISABLED = "Disabled"
	WATERTAXARVSTATUSDELETED  = "Deleted"
)
const (
	WATERTAXCONNECTIONTYPESTATUSACTIVE   = "Active"
	WATERTAXCONNECTIONTYPESTATUSDISABLED = "Disabled"
	WATERTAXCONNECTIONTYPESTATUSDELETED  = "Deleted"
)
