
[development]
database_name="ccknia"
mongodb_url="mongodb://127.0.0.1:27018,127.0.0.1:27019,127.0.0.1:27020/?replicaSet=rsSample"
WHATSAPP_URL = "https://whatsapp.ebotify.com/v1/messages?businessId="
WHATSAPP_BUSINESSID = "d67e5a20-47aa-11ec-9728-1d2a8519b5ab"
WEATHERDATA_URL ="https://api.openweathermap.org/data/2.5/onecall?"
WEATHERDATA_ID ="ec7677323aeaee1ab36973ae4f96c3c5"
SMS_URL = "http://bulk.smseasy.in/api/mt/SendSMS"
SMS_URL_BKUP = "http://sms.logikoof.com/api/mt/SendSMS"
SMS_USERNAME="nicekn"
SMS_PASSWORD="nicekn1"
SMS_SENDER_ID="NICEKN"
SMS_CHANNEL="Trans"
SMS_DCS=0
SMS_FLASH=0
SMS_ROUTE="1"
EMAIL_FROM="solomon@logikoof.in" 
EMAIL_FROM_PASSWORD="#nature32"
EMAIL_SMTPHOST="smtp.yandex.com"
EMAIL_SMTPPORT="587"
BASE_URL="http://stage.municipal.com"
API_BASE_URL="https://nicedemo.logikoof.org/api"
LOGIN_URL="/#/login"
CONTACTUS_URL="/#/contact"
FILE_URL = "C:/projects/nicessm/files/documents/"
COMPENDIUM_FILE_URL = "C:/projects/nicessm/files/"
FILE_URL_D = "documents/"
TEMPLATE_URL = "C:/projects/nicessm/files/templates/"
LOCATION_NAME = "Silao Nagar Panchayat"
UI_URL = "UI_URL"
LOGIN_URLV2 = "https://nicessm.org/"
PUSHNOTIFICATION_CRED = "C:/solo/repos/nicessm/files/config/nice-f870c-firebase-adminsdk-tpza7-3955373783.json"


[test]
database_name="ccknia"
mongodb_url="mongodb://localhost:27018,localhost:27019,localhost:27020/?replicaSet=rsSample"
#mongodb_url="mongodb://localhost:27018,localhost:27019,localhost:27020/?replicaSet=rsSample&readPreference=secondary&maxStalenessSeconds=120"
WHATSAPP_URL = "https://whatsapp.ebotify.com/v1/messages?businessId="
WHATSAPP_BUSINESSID = "d67e5a20-47aa-11ec-9728-1d2a8519b5ab"
WEATHERDATA_URL ="https://api.openweathermap.org/data/2.5/onecall?"
WEATHERDATA_ID ="ec7677323aeaee1ab36973ae4f96c3c5"
SMS_URL_BKUP = "http://bulk.smseasy.in/api/mt/SendSMS"
SMS_URL = "http://sms.logikoof.com/api/mt/SendSMS"
SMS_USERNAME="nicekn"
SMS_PASSWORD="nicekn1"
SMS_SENDER_ID="NICEKN"
SMS_CHANNEL="Trans"
SMS_DCS=0
SMS_FLASH=0
SMS_ROUTE="1"
EMAIL_FROM="solomon@logikoof.in" 
EMAIL_FROM_PASSWORD="#nature32"
EMAIL_SMTPHOST="smtp.yandex.com"
EMAIL_SMTPPORT="587"
BASE_URL="http://stage.municipal.com"
API_BASE_URL="https://nicedemo.logikoof.org/api"
LOGIN_URL="/#/login"
CONTACTUS_URL="/#/contact"
FILE_URL = "C:/projects/nicessm/files/documents/"
FILE_URL_D = "documents/"
COMPENDIUM_FILE_URL = "C:/projects/nicessm/files/"
TEMPLATE_URL = "C:/projects/nicessm/files/templates/"
LOCATION_NAME = "Silao Nagar Panchayat"
UI_URL = "C:/solo/repos/nicessm/dist/"
PUSHNOTIFICATION_CRED = "C:/solo/repos/nicessm/files/config/nice-f870c-firebase-adminsdk-tpza7-3955373783.json"

[stage]
database_name="cckniastage"
mongodb_url="mongodb://localhost:27018,localhost:27019,localhost:27020/?replicaSet=rsSample"
WHATSAPP_URL = "https://whatsapp.ebotify.com/v1/messages?businessId="
WHATSAPP_BUSINESSID = "d67e5a20-47aa-11ec-9728-1d2a8519b5ab"
WEATHERDATA_URL ="https://api.openweathermap.org/data/2.5/onecall?"
WEATHERDATA_ID ="ec7677323aeaee1ab36973ae4f96c3c5"
SMS_URL = "http://bulk.smseasy.in/api/mt/SendSMS"
SMS_URL_BKUP = "http://sms.logikoof.com/api/mt/SendSMS"
SMS_USERNAME="nicekn"
SMS_PASSWORD="nicekn1"
SMS_SENDER_ID="NICEKN"
SMS_CHANNEL="Trans"
SMS_DCS=0
SMS_FLASH=0
SMS_ROUTE="1"
EMAIL_FROM="solomon@logikoof.in" 
EMAIL_FROM_PASSWORD="#nature32"
EMAIL_SMTPHOST="smtp.yandex.com"
EMAIL_SMTPPORT="587"
BASE_URL="http://stage.municipal.com"
API_BASE_URL="https://hrms.logikoof.com/api"
LOGIN_URL="/#/login"
CONTACTUS_URL="/#/contact"
FILE_URL = "C:/projects/nicessm/files/documents/"
FILE_URL_D = "documents/"
COMPENDIUM_FILE_URL = "C:/projects/nicessm/files/"
TEMPLATE_URL = "C:/projects/nicessm/files/templates/"
LOCATION_NAME = "Silao Nagar Panchayat"
UI_URL = "UI_URL"
PUSHNOTIFICATION_CRED = "C:/solo/repos/harit/files/config/nice-f870c-firebase-adminsdk-tpza7-3955373783.json"



[jnkvdev]
database_name="mpkv"
mongodb_url="mongodb://localhost:27017"
WHATSAPP_URL = "https://whatsapp.ebotify.com/v1/messages?businessId="
WHATSAPP_BUSINESSID = "d67e5a20-47aa-11ec-9728-1d2a8519b5ab"
WEATHERDATA_URL ="https://api.openweathermap.org/data/2.5/onecall?"
WEATHERDATA_ID ="ec7677323aeaee1ab36973ae4f96c3c5"
SMS_URL = "http://bulk.smseasy.in/api/mt/SendSMS"
SMS_URL_BKUP = "http://sms.logikoof.com/api/mt/SendSMS"
SMS_USERNAME="nicekn"
SMS_PASSWORD="nicekn"
SMS_SENDER_ID="NICEKN"
SMS_CHANNEL="Trans"
SMS_DCS=0
SMS_FLASH=0
SMS_ROUTE="1"
EMAIL_FROM="solomon@logikoof.in" 
EMAIL_FROM_PASSWORD="#nature32"
EMAIL_SMTPHOST="smtp.yandex.com"
EMAIL_SMTPPORT="587"
BASE_URL="https://jnkvdev.logikoof.org"
API_BASE_URL="https://jnkvdev.logikoof.org/api"
LOGIN_URL="/#/login"
CONTACTUS_URL="/#/contact"
FILE_URL = "C:/solo/repos/nicessm/files/documents/"
FILE_URL_D = "documents/"
COMPENDIUM_FILE_URL = "C:/solo/repos/nicessm/files"
TEMPLATE_URL = "C:/solo/repos/nicessm/files/documents/templates/"
LOCATION_NAME = "JNKV Dev"
UI_URL = "C:/solo/repos/nicessm/dist/"
PUSHNOTIFICATION_CRED = "C:/solo/repos/nicessm/files/config/nice-f870c-firebase-adminsdk-tpza7-3955373783.json"



[jnkv]
database_name="jnkv"
mongodb_url="mongodb://localhost:27018,localhost:27019,localhost:27020,localhost:27021,localhost:27022/?replicaSet=rsSample"
WHATSAPP_URL = "https://whatsapp.ebotify.com/v1/messages?businessId="
WHATSAPP_BUSINESSID = "d67e5a20-47aa-11ec-9728-1d2a8519b5ab"
WEATHERDATA_URL ="https://api.openweathermap.org/data/2.5/onecall?"
WEATHERDATA_ID ="ec7677323aeaee1ab36973ae4f96c3c5"
SMS_URL = "http://bulk.smseasy.in/api/mt/SendSMS"
SMS_URL_BKUP = "http://sms.logikoof.com/api/mt/SendSMS"
SMS_USERNAME="nicekn"
SMS_PASSWORD="nicekn1"
SMS_SENDER_ID="NICEKN"
SMS_CHANNEL="Trans"
SMS_DCS=0
SMS_FLASH=0
SMS_ROUTE="1"
EMAIL_FROM="solomon@logikoof.in" 
EMAIL_FROM_PASSWORD="#nature32"
EMAIL_SMTPHOST="smtp.yandex.com"
EMAIL_SMTPPORT="587"
BASE_URL="http://stage.municipal.com"
API_BASE_URL="https://jnkv.nicessm.org/api"
LOGIN_URL="/#/login"
CONTACTUS_URL="/#/contact"
FILE_URL = "C:/projects/jnkv/files/documents/"
FILE_URL_D = "documents/"
COMPENDIUM_FILE_URL = "C:/projects/jnkv/files/"
TEMPLATE_URL = "C:/projects/jnkv/files/documents/templates/"
LOCATION_NAME = "JNKV"
UI_URL = "UI_URL"
LOGIN_URLV2 = "https://jnkv.nicessm.org/"
PUSHNOTIFICATION_CRED = "C:/projects/jnkv/config/jnkv-mobile-app-firebase-adminsdk-mopdw-38ccbfdc66.json"

[mpkv]
database_name="mpkv"
mongodb_url="mongodb://127.0.0.1:27017"
WHATSAPP_URL = "https://whatsapp.ebotify.com/v1/messages?businessId="
WHATSAPP_BUSINESSID = "d67e5a20-47aa-11ec-9728-1d2a8519b5ab"
WEATHERDATA_URL ="https://api.openweathermap.org/data/2.5/onecall?"
WEATHERDATA_ID ="ec7677323aeaee1ab36973ae4f96c3c5"
SMS_URL = "http://bulk.smseasy.in/api/mt/SendSMS"
SMS_URL_BKUP = "http://sms.logikoof.com/api/mt/SendSMS"
SMS_USERNAME="nicekn"
SMS_PASSWORD="nicekn1"
SMS_SENDER_ID="NICEKN"
SMS_CHANNEL="Trans"
SMS_DCS=0
SMS_FLASH=0
SMS_ROUTE="1"
EMAIL_FROM="solomon@logikoof.in" 
EMAIL_FROM_PASSWORD="#nature32"
EMAIL_SMTPHOST="smtp.yandex.com"
EMAIL_SMTPPORT="587"
BASE_URL="http://stage.municipal.com"
API_BASE_URL="https://mpkv.nicessm.org/api"
LOGIN_URL="/#/login"
CONTACTUS_URL="/#/contact"
FILE_URL = "C:/projects/mpkv/files/documents/"
FILE_URL_D = "documents/"
COMPENDIUM_FILE_URL = "C:/projects/mpkv/files/"
TEMPLATE_URL = "C:/projects/mpkv/files/documents/templates/"
LOCATION_NAME = "MPKV"
UI_URL = "UI_URL"
LOGIN_URLV2 = "https://mpkv.nicessm.org/"
PUSHNOTIFICATION_CRED = "C:/projects/mpkv/config/mpkv-mobile-app-firebase-adminsdk-ntl4j-52ae4ed276.json"

[jnkvdup]
database_name="jnkvdup"
mongodb_url="mongodb://127.0.0.1:27018,127.0.0.1:27019,127.0.0.1:27020,127.0.0.1:27021,127.0.0.1:27022/?replicaSet=rsProd"
WHATSAPP_URL = "https://whatsapp.ebotify.com/v1/messages?businessId="
WHATSAPP_BUSINESSID = "d67e5a20-47aa-11ec-9728-1d2a8519b5ab"
WEATHERDATA_URL ="https://api.openweathermap.org/data/2.5/onecall?"
WEATHERDATA_ID ="ec7677323aeaee1ab36973ae4f96c3c5"
SMS_URL = "http://bulk.smseasy.in/api/mt/SendSMS"
SMS_URL_BKUP = "http://sms.logikoof.com/api/mt/SendSMS"
SMS_USERNAME="nicekn"
SMS_PASSWORD="nicekn1"
SMS_SENDER_ID="NICEKN"
SMS_CHANNEL="Trans"
SMS_DCS=0
SMS_FLASH=0
SMS_ROUTE="1"
EMAIL_FROM="solomon@logikoof.in" 
EMAIL_FROM_PASSWORD="#nature32"
EMAIL_SMTPHOST="smtp.yandex.com"
EMAIL_SMTPPORT="587"
BASE_URL="http://stage.municipal.com"
API_BASE_URL="https://mpkv.nicessm.org/api"
LOGIN_URL="/#/login"
CONTACTUS_URL="/#/contact"
FILE_URL = "C:/solo/repos/nicessm/files/documents/"
FILE_URL_D = "documents/"
COMPENDIUM_FILE_URL = "C:/solo/repos/nicessm/files"
TEMPLATE_URL = "C:/solo/repos/nicessm/files/documents/templates/"
LOCATION_NAME = "MPKV"
UI_URL = "UI_URL"
LOGIN_URLV2 = "https://mpkv.nicessm.org/"
PUSHNOTIFICATION_CRED = "C:/projects/mpkv/config/mpkv-mobile-app-firebase-adminsdk-ntl4j-52ae4ed276.json"
