package constants

const (
	COLLECTIONBLOCKWEATHERDATA    = "blockWeatherData"
	BLOCKWEATHERDATASTATUSTRUE    = true
	BLOCKWEATHERDATASTATUSFALSE   = false
	BLOCKWEATHERDATASTATUSACTIVE  = "Active"
	BLOCKWEATHERDATASTATUSDISABLE = "Disabled"
	BLOCKWEATHERDATASTATUSDELETED = "Deleted"
)
const (
	IMD_BLOCKWEATHERDATA_URL      = "IMD_BLOCKWEATHERDATA_URL"
	IMD_BLOCKWEATHERDATA_FILE     = "IMD_BLOCKWEATHERDATA_FILE"
	IMD_BLOCKWEATHERDATA_LOCATION = "IMD_BLOCKWEATHERDATA_LOCATION"
)
