package constants

const (
	COLLECTIONDISTRICWEATHERDATA    = "districtWeatherData"
	DISTRICWEATHERDATASTATUSTRUE    = true
	DISTRICWEATHERDATASTATUSFALSE   = false
	DISTRICWEATHERDATASTATUSACTIVE  = "Active"
	DISTRICWEATHERDATASTATUSDISABLE = "Disabled"
	DISTRICWEATHERDATASTATUSDELETED = "Deleted"
)

const (
	WEATHERDATA_URL = "WEATHERDATA_URL"

	WEATHERDATA_ID = "WEATHERDATA_ID"
)
const (
	IMDWEATHERDATA_URL = "IMD_WEATHERDATA_URL"

	IMDWEATHERDATA_FILE     = "IMD_WEATHERDATA_FILE"
	IMDWEATHERDATA_LOCATION = "IMD_WEATHERDATA_LOCATION"
)
