package constants

const (
	COLLECTIONGRAMPANCHAYATWEATHERDATA    = "grampanchayatWeatherData"
	GRAMPANCHAYATWEATHERDATASTATUSTRUE    = true
	GRAMPANCHAYATWEATHERDATASTATUSFALSE   = false
	GRAMPANCHAYATWEATHERDATASTATUSACTIVE  = "Active"
	GRAMPANCHAYATWEATHERDATASTATUSDISABLE = "Disabled"
	GRAMPANCHAYATWEATHERDATASTATUSDELETED = "Deleted"
)
