package constants

const (
	IMDDISTRICT       = "district"
	IMDBLOCK          = "block"
	IMDmaxlength      = "maxlength"
	IMDstate2         = "state2"
	IMDstate1         = "state1"
	IMDdistrict2      = "district2"
	IMDdistrict1      = "district1"
	IMDBlock1         = "block1"
	IMDlat1           = "lat1"
	IMDlong1          = "long1"
	IMDalto1          = "alto1"
	IMDpcod1          = "pcod1"
	IMDday1           = "day1"
	IMDmonth1         = "month1"
	IMDyear1          = "year1"
	IMDmspl1          = "mspl1"
	IMDicid1          = "icid1"
	IMDrainfall1      = "rainfall1"
	IMDmaxtemp1       = "maxtemp1"
	IMDmintemp1       = "mintemp1"
	IMDmaxrelhum1     = "maxrelhum1"
	IMDminremhum1     = "minremhum1"
	IMDwindspeed1     = "windspeed1"
	IMDwinddirection1 = "winddirection1"
	IMDBlock2         = "block2"
	IMDlat2           = "lat2"
	IMDlong2          = "long2"
	IMDalto2          = "alto2"
	IMDpcod2          = "pcod2"
	IMDday2           = "day2"
	IMDmonth2         = "month2"
	IMDyear2          = "year2"
	IMDmspl2          = "mspl2"
	IMDicid2          = "icid2"
	IMDrainfall2      = "rainfall2"
	IMDmaxtemp2       = "maxtemp2"
	IMDmintemp2       = "mintemp2"
	IMDmaxrelhum2     = "maxrelhum2"
	IMDminremhum2     = "minremhum2"
	IMDwindspeed2     = "windspeed2"
	IMDwinddirection2 = "winddirection2"
)
