package constants

//Notification Constants
const (
	NOTIFICATIONSTATUSACTIVE   = "Active"
	NOTIFICATIONSTATUSDISABLED = "Disabled"
	NOTIFICATIONSTATUSDELETED  = "Deleted"
)

const (
	NOTIFICATIONTYPESMS    = "SMS"
	NOTIFICATIONTYPENOTIFY = "NOTIFY"
	NOTIFICATIONTYPESMSV2  = "SMSV2"
)
