package constants

const (
	COLLECTIONSTATEWEATHERDATA    = "statetWeatherData"
	STATEWEATHERDATASTATUSTRUE    = true
	STATEWEATHERDATASTATUSFALSE   = false
	STATEWEATHERDATASTATUSACTIVE  = "Active"
	STATEWEATHERDATASTATUSDISABLE = "Disabled"
	STATEWEATHERDATASTATUSDELETED = "Deleted"
)
