package constants

const (
	COLLECTIONVILLAGEWEATHERDATA    = "villageWeatherData"
	VILLAGEWEATHERDATASTATUSTRUE    = true
	VILLAGEWEATHERDATASTATUSFALSE   = false
	VILLAGEWEATHERDATASTATUSACTIVE  = "Active"
	VILLAGEWEATHERDATASTATUSDISABLE = "Disabled"
	VILLAGEWEATHERDATASTATUSDELETED = "Deleted"
)
