package constants

const (
	WEATHERPARAMETERSTATUSACTIVE  = "Active"
	WEATHERPARAMETERSTATUSDISABLE = "Disabled"
	WEATHERPARAMETERSTATUSDELETED = "Deleted"
	WEATHERPARAMETERRAINFALL      = "Rainfall"
	WEATHERPARAMETERTEMPERATURE   = "Temperature"
	WEATHERPARAMETERHUMIDITY      = "Humidity"
	WEATHERPARAMETERWINDSPEED     = "WindSpeed"
	WEATHERPARAMETERWINDDIRECTION = "WindDirection"
)
