package constants

// Attendance Constants
const (
	ATTENDANCESTATUSACTIVE       = "Active"
	ATTENDANCESTATUSLEAVE        = "Leave"
	ATTENDANCESTATUSDISABLED     = "Disabled"
	ATTENDANCESTATUSDELETED      = "Deleted"
	EMPLOYEESTATUSDISABLED       = "Disabled"
	EMPLOYEESTATUSDELETED        = "Deleted"
	EMPLOYEESTATUSRELIEVE        = "Relieve"
	EMPLOYEESTATUSONBORADING     = "Onboarding"
	EMPLOYEESTATUSREJECT         = "Reject"
	ATTENDANCESTATUSLOP          = "LOP"
	ATTENDANCESTATUSPAID         = "Paid"
	ATTENDANCESTATUSPARTIALPAY   = "PartialPay"
	ATTENDANCESTATUSLOGIN        = "Login"
	ATTENDANCESTATUSAUTO         = "Auto"
	ATTENDANCESTATUSTIMEOFF      = "TimeOff"
	ATTENDANCESTATUSLOGOUT       = "Logout"
	ATTENDANCEMANUALSTATUSLOGOUT = "MANUALUPDATED"
	DDMMYYYY                     = "02/01/2006"
	ATTENDANCESTATUSREQUEST      = "Request"
	ATTENDANCESTATUSPENDING      = "Pending"
	ATTENDANCESTATUSAPPROVE      = "Approved"
	ATTENDANCESTATUSREJECT       = "Reject"
	HOURS                        = "hours"
	MINS                         = "mins"
	EMPLOYEETIMEOFFSTATUSREQUEST = "Request"
)

// AttendanceLog Constants
const (
	ATTENDANCELOGSTATUSACTIVE   = "Active"
	ATTENDANCELOGSTATUSDISABLED = "Disabled"
	ATTENDANCELOGSTATUSDELETED  = "Deleted"
)
