package constants

//Bank Constants
const (
	BANKINFORMATIONSTATUSACTIVE   = "Active"
	BANKINFORMATIONSTATUSDISABLED = "Disabled"
	BANKINFORMATIONSTATUSDELETED  = "Deleted"
)

//Salary Constants
const (
	SALARYSTATUSACTIVE   = "Active"
	SALARYSTATUSDISABLED = "Disabled"
	SALARYSTATUSDELETED  = "Deleted"
)

//Payment Constants
const (
	PAYMENTSTATUSACTIVE   = "Active"
	PAYMENTSTATUSDISABLED = "Disabled"
	PAYMENTSTATUSDELETED  = "Deleted"
	PAYMENTSTATUSPENDING  = "Pending"
	PAYMENTSTATUSACCEPT   = "Accept"
	PAYMENTSTATUSREJECT   = "Reject"
	PAYMENTSTATUSRECEVIED = "Recevied"
)

//Employee Earning Master Constants
const (
	EMPLOYEEEARNINGMASTERSTATUSACTIVE   = "Active"
	EMPLOYEEEARNINGMASTERSTATUSDISABLED = "Disabled"
	EMPLOYEEEARNINGMASTERSTATUSDELETED  = "Deleted"
)

//Employee Deduction Mater Constants
const (
	EMPLOYEEDEDUCTIONMASTERSTATUSACTIVE   = "Active"
	EMPLOYEEDEDUCTIONMASTERSTATUSDISABLED = "Disabled"
	EMPLOYEEDEDUCTIONMASTERSTATUSDELETED  = "Deleted"
)

//Employee Earning Constants
const (
	EMPLOYEEEARNINGSTATUSACTIVE   = "Active"
	EMPLOYEEEARNINGSTATUSDISABLED = "Disabled"
	EMPLOYEEEARNINGSTATUSDELETED  = "Deleted"
)

//Employee Deduction Constants
const (
	EMPLOYEEDEDUCTIONSTATUSACTIVE   = "Active"
	EMPLOYEEDEDUCTIONSTATUSDISABLED = "Disabled"
	EMPLOYEEDEDUCTIONSTATUSDELETED  = "Deleted"
	EMPLOYEEDEDUCTIONTYPEPF         = "PF"
)

//Employee Payroll Constants
const (
	EMPLOYEEPAYROLLSTATUSACTIVE   = "Active"
	EMPLOYEEPAYROLLSTATUSDISABLED = "Disabled"
	EMPLOYEEPAYROLLSTATUSDELETED  = "Deleted"
	EMPLOYEEPAYROLLSTATUSARCHIVED = "Archived"
)
