package constants

//FUELHISTORY Constants
const (
	FUELHISTORYSTATUSACTIVE   = "Active"
	FUELHISTORYSTATUSDISABLED = "Disabled"
	FUELHISTORYSTATUSDELETED  = "Deleted"
	FUELHISTORYSTATUSINIT     = "Init"
)
