package constants

const (
	COLLECTIONNOTIFICATIONLOG    = "notificationlog"
	NOTIFICATIONLOGSTATUSTRUE    = true
	NOTIFICATIONLOGSTATUSFALSE   = false
	NOTIFICATIONLOGSTATUSACTIVE  = "Active"
	NOTIFICATIONLOGSTATUSDISABLE = "Disabled"
	NOTIFICATIONLOGSTATUSDELETED = "Deleted"
)
