package constants

//offboardingCheckList Constants
const (
	OFFBOARDINGCHECKLISTSTATUSACTIVE   = "Active"
	OFFBOARDINGCHECKLISTSTATUSDISABLED = "Disabled"
	OFFBOARDINGCHECKLISTSTATUSDELETED  = "Deleted"
)

//OffboardingCheckListMaster Constants
const (
	OFFBOARDINGCHECKLISTMASTERSTATUSACTIVE   = "Active"
	OFFBOARDINGCHECKLISTMASTERSTATUSDISABLED = "Disabled"
	OFFBOARDINGCHECKLISTMASTERSTATUSDELETED  = "Deleted"
)

//OffboardingPolicy Constants
const (
	OFFBOARDINGPOLICYSTATUSACTIVE   = "Active"
	OFFBOARDINGPOLICYSTATUSDISABLED = "Disabled"
	OFFBOARDINGPOLICYSTATUSDELETED  = "Deleted"
)
