package constants

//onboardingCheckList Constants
const (
	ONBOARDINGCHECKLISTSTATUSACTIVE   = "Active"
	ONBOARDINGCHECKLISTSTATUSDISABLED = "Disabled"
	ONBOARDINGCHECKLISTSTATUSDELETED  = "Deleted"
)

//onboardingCheckListMaster Constants
const (
	ONBOARDINGCHECKLISTMASTERSTATUSACTIVE   = "Active"
	ONBOARDINGCHECKLISTMASTERSTATUSDISABLED = "Disabled"
	ONBOARDINGCHECKLISTMASTERSTATUSDELETED  = "Deleted"
)

//onboardingPolicy Constants
const (
	ONBOARDINGPOLICYSTATUSACTIVE   = "Active"
	ONBOARDINGPOLICYSTATUSDISABLED = "Disabled"
	ONBOARDINGPOLICYSTATUSDELETED  = "Deleted"
)
