package constants

const (
	ORGANISATIONCONFIGSTATUSTRUE    = true
	ORGANISATIONCONFIGSTATUSFALSE   = false
	ORGANISATIONCONFIGSTATUSACTIVE  = "Active"
	ORGANISATIONCONFIGSTATUSDISABLE = "Disabled"
	ORGANISATIONCONFIGSTATUSDELETED = "Deleted"
)
