package constants

const (
	VECHILESTATUSACTIVE   = "Active"
	VECHILESTATUSINACTIVE = "InActive"
	VECHILESTATUSDISABLED = "Disabled"
	VECHILESTATUSDELETED  = "Deleted"
	VECHILESTATUSASSIGN   = "Assigned"
	VECHILESTATUSREVOKE   = "Revoked"
)
