package constants

//VEHICLEINSURANCE Constants
const (
	VEHICLEINSURANCESTATUSACTIVE   = "Active"
	VEHICLEINSURANCESTATUSDISABLED = "Disabled"
	VEHICLEINSURANCESTATUSDELETED  = "Deleted"
	VEHICLEINSURANCESTATUSINIT     = "Init"
)
