package constants

//VEHICLETYPE Constants
const (
	VEHICLETYPESTATUSACTIVE   = "Active"
	VEHICLETYPESTATUSDISABLED = "Disabled"
	VEHICLETYPESTATUSDELETED  = "Deleted"
	VEHICLETYPESTATUSINIT     = "Init"
)
