package constants

// VEHICLELOCATION Constants
const (
	VEHICLELOCATIONSTATUSACTIVE   = "Active"
	VEHICLELOCATIONSTATUSDISABLED = "Disabled"
	VEHICLELOCATIONSTATUSDELETED  = "Deleted"
)
const (
	VEHICLETRIPSTATUSACTIVE   = "Active"
	VEHICLETRIPSTATUSDISABLED = "Disabled"
	VEHICLETRIPSTATUSDELETED  = "Deleted"
)
