package constants

//VEHICLELOG Constants
const (
	VEHICLELOGSTATUSACTIVE   = "Active"
	VEHICLELOGSTATUSDISABLED = "Disabled"
	VEHICLELOGSTATUSDELETED  = "Deleted"
	VEHICLELOGSTATUSINIT     = "Init"
)

const (
	AREAASSIGNLOGSTATUSACTIVE   = "Active"
	AREAASSIGNLOGSTATUSDISABLED = "Disabled"
	AREAASSIGNLOGSTATUSDELETED  = "Deleted"
	AREAASSIGNLOGSTATUSINIT     = "Init"
)
