package constants

const (
	WASTECOLLECTEDSTATUSACTIVE       = "Active"
	WASTECOLLECTEDSTATUSDISABLED     = "Disabled"
	WASTECOLLECTEDSTATUSCOMPLETED    = "Completed"
	WASTECOLLECTEDSTATUSPENDING      = "Pending"
	WASTECOLLECTEDSTATUSDELETED      = "Deleted"
	WASTECOLLECTEDSTATUSNOTAVAILABLE = "NotAvailable"
)
const (
	HOUSEVISITEDSTATUSACTIVE       = "Active"
	HOUSEVISITEDSTATUSDISABLED     = "Disabled"
	HOUSEVISITEDSTATUSDELETED      = "Deleted"
	HOUSEVISITEDSTATUSCOLLECTED    = "Collected"
	HOUSEVISITEDSTATUSNOTAVAILABLE = "NotAvailable"
)
const (
	MYSURVEYSTATUSACTIVE   = "Active"
	MYSURVEYSTATUSDISABLED = "Disabled"
	MYSURVEYSTATUSDELETED  = "Deleted"
)
const (
	SERVICEREQUESTSTATUSACTIVE     = "Active"
	SERVICEREQUESTSTATUSDISABLED   = "Disabled"
	SERVICEREQUESTSTATUSDELETED    = "Deleted"
	SERVICEREQUESTSTATUSINIT       = "Init"
	SERVICEREQUESTSTATUSPENDING    = "Pending"
	SERVICEREQUESTSTATUSINPROGRESS = "InProgress"
	SERVICEREQUESTSTATUSCOMPLETED  = "Completed"
)
