[development]
database_name="munger"
mongodb_url="mongodb://localhost:27017"
SMS_URL = "http://sms.logikoof.com/api/mt/SendSMS"
SMS_USERNAME="logikoof"
SMS_PASSWORD="logikoof"
SMS_SENDER_ID="LOGIKF"
SMS_CHANNEL="Trans"
SMS_DCS=0
SMS_FLASH=0
SMS_ROUTE="1"
EMAIL_FROM="bpmsdevelopment@gmail.com" 
EMAIL_FROM_PASSWORD="#nature32"
EMAIL_SMTPHOST="smtp.gmail.com"
EMAIL_SMTPPORT="587"
BASE_URL="http://municipal.logikoof.in"
API_BASE_URL=" http://api.municipal.logikoof.in"
LOGIN_URL="/#/login"
CONTACTUS_URL="/#/contact"
FILE_URL = "C:/solo/repos/silaostage/files/documents/"
FILE_URL_D = "/documents/"
TEMPLATE_URL = "C:/solo/repos/silaostage/files/templates/"
STRIP_DOC_LOC = "/documents/"
DOC_LOC_URL = "/documents/{folder1}/{file}"
PROPERTY_DEMAND_CRON = "30 22 * * 2,4,6"
PROPERTY_DASHBOARD_CRON = "30 09-22 * * *"


[local]
database_name="bhagalpur"
mongodb_url="mongodb://localhost:27018,localhost:27019,localhost:27020/?replicaSet=rsSample"
SMS_URL = "https://msg.smseasy.in/SMSApi/send"
SMS_URL_BKUP = "http://sms.logikoof.com/api/mt/SendSMS"
SMS_USERNAME="brmncp"
SMS_PASSWORD="brmncp"
SMS_SENDER_ID="BRMNCP"
SMS_CHANNEL="Trans"
SMS_DCS=0
SMS_FLASH=0
SMS_ROUTE="1"
SEND_METHOD="quick" 
SEND_MSGTYPE="text"
SEND_DUPLICATECHK="true"
SEND_OUTPUT="json"
EMAIL_FROM="noreply@biharmunicipal.com" 
EMAIL_FROM_PASSWORD="8f92c5a065e3ca4d53e23f6f28427502-b2f5ed24-087999df"
EMAIL_SMTPHOST="smtp.mailgun.org"
EMAIL_SMTPPORT="587"
BASE_URL="http://stage.municipal.com"
API_BASE_URL=" http://apistage.municipal.com"
LOGIN_URL="/#/login"
CONTACTUS_URL="/#/contact"
FILE_URL = "C:/solo/repos/silaostage/files/documents/"
FILE_URL_D = "/documents/"
TEMPLATE_URL = "C:/solo/repos/silaostage/files/templates/"
LOCATION_NAME = "Silao Nagar Panchayat"
STRIP_DOC_LOC = "/documents/"
DOC_LOC_URL = "/documents/{folder1}/{file}"
PROPERTY_DEMAND_CRON = "30 22 * * 2,4,6"
PROPERTY_DASHBOARD_CRON = "30 09-22 * * *"


[gorakhpur]
database_name="gorakhpur"
mongodb_url="mongodb://localhost:27018,localhost:27019,localhost:27020/?replicaSet=rsSample"
SMS_URL = "http://bulk.smseasy.in/api/mt/SendSMS"
SMS_URL_BKUP = "http://sms.logikoof.com/api/mt/SendSMS"
SMS_USERNAME="BRMNCP"
SMS_PASSWORD="BRMNCP"
SMS_SENDER_ID="BRMNCP"
SMS_CHANNEL="Trans"
SMS_DCS=0
SMS_FLASH=0
SMS_ROUTE="1"
EMAIL_FROM="noreply@biharmunicipal.com" 
EMAIL_FROM_PASSWORD="8f92c5a065e3ca4d53e23f6f28427502-b2f5ed24-087999df"
EMAIL_SMTPHOST="smtp.mailgun.org"
EMAIL_SMTPPORT="587"
BASE_URL="http://stage.municipal.com"
API_BASE_URL=" http://apistage.municipal.com"
LOGIN_URL="/#/login"
CONTACTUS_URL="/#/contact"
FILE_URL = "C:/solo/repos/silaostage/files/documents/"
FILE_URL_D = "/documents/"
TEMPLATE_URL = "C:/solo/repos/silaostage/files/templates/"
LOCATION_NAME = "Silao Nagar Panchayat"
STRIP_DOC_LOC = "/documents/"
DOC_LOC_URL = "/documents/{folder1}/{file}"
PROPERTY_DEMAND_CRON = "30 22 * * 2,4,6"
PROPERTY_DASHBOARD_CRON = "30 09-22 * * *"





[silaostage]
database_name="ramnagar"
mongodb_url="mongodb://localhost:27017"
SMS_URL = "http://bulk.smseasy.in/api/mt/SendSMS"
SMS_URL_BKUP = "http://sms.logikoof.com/api/mt/SendSMS"
SMS_USERNAME="BRMNCP"
SMS_PASSWORD="BRMNCP"
SMS_SENDER_ID="BRMNCP"
SMS_CHANNEL="Trans"
SMS_DCS=0
SMS_FLASH=0
SMS_ROUTE="1"
EMAIL_FROM="noreply@biharmunicipal.com" 
EMAIL_FROM_PASSWORD="8f92c5a065e3ca4d53e23f6f28427502-b2f5ed24-087999df"
EMAIL_SMTPHOST="smtp.mailgun.org"
EMAIL_SMTPPORT="587"
BASE_URL="http://stage.municipal.com"
API_BASE_URL=" http://apistage.municipal.com"
LOGIN_URL="/#/login"
CONTACTUS_URL="/#/contact"
FILE_URL = "C:/solo/repos/silaostage/files/documents/"
FILE_URL_D = "/documents/"
TEMPLATE_URL = "C:/solo/repos/silaostage/files/templates/"
LOCATION_NAME = "Silao Nagar Panchayat"
STRIP_DOC_LOC = "/documents/"
DOC_LOC_URL = "/documents/{folder1}/{file}"


[kochasstage]
database_name="kochasstage"
mongodb_url="mongodb://localhost:27018,localhost:27019,localhost:27020/?replicaSet=rsSample"
SMS_URL = "http://sms.logikoof.com/api/mt/SendSMS"
SMS_USERNAME="nicekn"
SMS_PASSWORD="nicekn"
SMS_SENDER_ID="NICEKN"
SMS_CHANNEL="Trans"
SMS_DCS=0
SMS_FLASH=0
SMS_ROUTE="1"
EMAIL_FROM="bpmsdevelopment@gmail.com" 
EMAIL_FROM_PASSWORD="#nature32"
EMAIL_SMTPHOST="smtp.gmail.com"
EMAIL_SMTPPORT="587"
BASE_URL="http://stage.municipal.com"
API_BASE_URL=" http://apistage.municipal.com"
LOGIN_URL="/#/login"
CONTACTUS_URL="/#/contact"
FILE_URL = "C:/solo/repos/kochasstage/files/documents/"
FILE_URL_D = "/documents/"
TEMPLATE_URL = "C:/solo/repos/kochasstage/files/templates/"
LOCATION_NAME = "Kochas Nagar Panchayat"
STRIP_DOC_LOC = "/documents/"
DOC_LOC_URL = "/documents/{folder1}/{file}"

[silaostest]
database_name="silaostest"
mongodb_url="mongodb://localhost:27018,localhost:27019,localhost:27020/?replicaSet=rsSample"
SMS_URL = "http://bulk.smseasy.in/api/mt/SendSMS"
SMS_URL_BKUP = "http://sms.logikoof.com/api/mt/SendSMS"
SMS_USERNAME="BRMNCP"
SMS_PASSWORD="BRMNCP"
SMS_SENDER_ID="BRMNCP"
SMS_CHANNEL="Trans"
SMS_DCS=0
SMS_FLASH=0
SMS_ROUTE="1"
EMAIL_FROM="noreply@biharmunicipal.com" 
EMAIL_FROM_PASSWORD="8f92c5a065e3ca4d53e23f6f28427502-b2f5ed24-087999df"
EMAIL_SMTPHOST="smtp.mailgun.org"
EMAIL_SMTPPORT="587"
BASE_URL="http://stage.municipal.com"
API_BASE_URL=" http://apistage.municipal.com"
LOGIN_URL="/#/login"
CONTACTUS_URL="/#/contact"
FILE_URL = "C:/solo/repos/silaostage/files/documents/"
FILE_URL_D = "/documents/"
TEMPLATE_URL = "C:/solo/repos/silaostage/files/templates/"
LOCATION_NAME = "Silao Nagar Panchayat"
STRIP_DOC_LOC = "/documents/"
DOC_LOC_URL = "/documents/{folder1}/{file}"

[selvalocal]
database_name="bhagalpur"
mongodb_url="mongodb://dbuser:Admin0912io129023@SG-mongoreplicaset-43872.servers.mongodirector.com:27017,SG-mongoreplicaset-43873.servers.mongodirector.com:27017,SG-mongoreplicaset-43874.servers.mongodirector.com:27017/admin?replicaSet=RS-mongoreplicaset-0"
mongodb_urlbkup="mongodb://localhost:27018,localhost:27019,localhost:27020/?replicaSet=rsSample"
SMS_URL = "http://bulk.smseasy.in/api/mt/SendSMS"
SMS_URL_BKUP = "http://sms.logikoof.com/api/mt/SendSMS"
SMS_USERNAME="BRMNCP"
SMS_PASSWORD="BRMNCP"
SMS_SENDER_ID="BRMNCP"
SMS_CHANNEL="Trans"
SMS_DCS=0
SMS_FLASH=0
SMS_ROUTE="1"
EMAIL_FROM="noreply@biharmunicipal.com" 
EMAIL_FROM_PASSWORD="8f92c5a065e3ca4d53e23f6f28427502-b2f5ed24-087999df"
EMAIL_SMTPHOST="smtp.mailgun.org"
EMAIL_SMTPPORT="587"
BASE_URL="http://stage.municipal.com"
API_BASE_URL=" http://apistage.municipal.com"
LOGIN_URL="/#/login"
CONTACTUS_URL="/#/contact"
FILE_URL = "C:/solo/repos/silaostage/files/documents/"
FILE_URL_D = "/documents/"
TEMPLATE_URL = "C:/solo/repos/silaostage/files/templates/"
LOCATION_NAME = "Silao Nagar Panchayat"
STRIP_DOC_LOC = "/documents/"
DOC_LOC_URL = "/documents/{folder1}/{file}"
PROPERTY_DEMAND_CRON = "30 22 * * 2,4,6"
PROPERTY_DASHBOARD_CRON = "30 09-22 * * *"


[local2222]
database_name="bhagalpur"
mongodb_url="mongodb://lgfmongodba:lgfdba#123@38.242.254.90:27020/"
SMS_URL = "http://bulk.smseasy.in/api/mt/SendSMS"
SMS_URL_BKUP = "http://sms.logikoof.com/api/mt/SendSMS"
SMS_USERNAME="BRMNCP"
SMS_PASSWORD="BRMNCP"
SMS_SENDER_ID="BRMNCP"
SMS_CHANNEL="Trans"
SMS_DCS=0
SMS_FLASH=0
SMS_ROUTE="1"
EMAIL_FROM="noreply@biharmunicipal.com" 
EMAIL_FROM_PASSWORD="8f92c5a065e3ca4d53e23f6f28427502-b2f5ed24-087999df"
EMAIL_SMTPHOST="smtp.mailgun.org"
EMAIL_SMTPPORT="587"
BASE_URL="http://stage.municipal.com"
API_BASE_URL=" http://apistage.municipal.com"
LOGIN_URL="/#/login"
CONTACTUS_URL="/#/contact"
FILE_URL = "C:/solo/repos/silaostage/files/documents/"
FILE_URL_D = "/documents/"
TEMPLATE_URL = "C:/solo/repos/silaostage/files/templates/"
LOCATION_NAME = "Silao Nagar Panchayat"
STRIP_DOC_LOC = "/documents/"
DOC_LOC_URL = "/documents/{folder1}/{file}"
PROPERTY_DEMAND_CRON = "30 22 * * 2,4,6"
PROPERTY_DASHBOARD_CRON = "30 09-22 * * *"



[Balalocal]
database_name="bhagalpur"
mongodb_url="mongodb://dbuser:Admin0912io129023@SG-mongoreplicaset-43872.servers.mongodirector.com:27017,SG-mongoreplicaset-43873.servers.mongodirector.com:27017,SG-mongoreplicaset-43874.servers.mongodirector.com:27017/admin?replicaSet=RS-mongoreplicaset-0"
mongodb_urlbkup="mongodb://localhost:27018,localhost:27019,localhost:27020/?replicaSet=rsSample"
SMS_URL = "http://bulk.smseasy.in/api/mt/SendSMS"
SMS_URL_BKUP = "http://sms.logikoof.com/api/mt/SendSMS"
SMS_USERNAME="BRMNCP"
SMS_PASSWORD="BRMNCP"
SMS_SENDER_ID="BRMNCP"
SMS_CHANNEL="Trans"
SMS_DCS=0
SMS_FLASH=0
SMS_ROUTE="1"
EMAIL_FROM="noreply@biharmunicipal.com" 
EMAIL_FROM_PASSWORD="8f92c5a065e3ca4d53e23f6f28427502-b2f5ed24-087999df"
EMAIL_SMTPHOST="smtp.mailgun.org"
EMAIL_SMTPPORT="587"
BASE_URL="http://stage.municipal.com"
API_BASE_URL=" http://apistage.municipal.com"
LOGIN_URL="/#/login"
CONTACTUS_URL="/#/contact"
FILE_URL = "C:/solo/repos/silaostage/files/documents/"
FILE_URL_D = "/documents/"
TEMPLATE_URL = "C:/solo/repos/silaostage/files/templates/"
LOCATION_NAME = "Silao Nagar Panchayat"
STRIP_DOC_LOC = "/documents/"
DOC_LOC_URL = "/documents/{folder1}/{file}"
PROPERTY_DEMAND_CRON = "30 22 * * 2,4,6"
PROPERTY_DASHBOARD_CRON = "30 09-22 * * *"
