package constants

// AssetPolicy Constants
const (
	ASSETPOLICYSTATUSACTIVE   = "Active"
	ASSETPOLICYSTATUSDISABLED = "Disabled"
	ASSETPOLICYSTATUSDELETED  = "Deleted"
)

// AssetMaster Constants
const (
	ASSETMASTERSTATUSACTIVE   = "Active"
	ASSETMASTERSTATUSDISABLED = "Disabled"
	ASSETMASTERSTATUSDELETED  = "Deleted"
)

// AssetPolicyAssets Constants
const (
	ASSETPOLICYASSETSSTATUSACTIVE   = "Active"
	ASSETPOLICYASSETSSTATUSDISABLED = "Disabled"
	ASSETPOLICYASSETSSTATUSDELETED  = "Deleted"
)

// Asset Constants
const (
	ASSETSTATUSACTIVE   = "Active"
	ASSETSTATUSDISABLED = "Disabled"
	ASSETSTATUSDELETED  = "Deleted"
)
const (
	ASSETASSIGNSTATUS    = "Assigned"
	ASSETREASSIGNSTATUS  = "ReAssign"
	ASSETREVOKESTATUS    = "Revoke"
	ASSETASSIGNSTATUSYES = "Yes"
	ASSETASSIGNSTATUSNO  = "No"
)

// AssetType Constants
const (
	ASSETTYPESTATUSACTIVE   = "Active"
	ASSETTYPESTATUSDISABLED = "Disabled"
	ASSETTYPESTATUSDELETED  = "Deleted"
)

// AssetTypePropertys Constants
const (
	ASSETTYPEPROPERTYSSTATUSACTIVE   = "Active"
	ASSETTYPEPROPERTYSSTATUSDISABLED = "Disabled"
	ASSETTYPEPROPERTYSSTATUSDELETED  = "Deleted"
)

// AssetPropertys Constants
const (
	ASSETPROPERTYSSTATUSACTIVE   = "Active"
	ASSETPROPERTYSSTATUSDISABLED = "Disabled"
	ASSETPROPERTYSSTATUSDELETED  = "Deleted"
)

// EmployeeAssets Constants
const (
	EMPLOYEEASSETSSTATUSACTIVE   = "Active"
	EMPLOYEEASSETSSTATUSDISABLED = "Disabled"
	EMPLOYEEASSETSSTATUSDELETED  = "Deleted"
)

// AssetLog Constants
const (
	ASSETLOGSTATUSACTIVE   = "Active"
	ASSETLOGSTATUSDISABLED = "Disabled"
	ASSETLOGSTATUSDELETED  = "Deleted"
)
