package constants

//BillclaimLevels Constants
const (
	BILLCLAIMLEVELSSTATUSACTIVE   = "Active"
	BILLCLAIMLEVELSSTATUSDISABLED = "Disabled"
	BILLCLAIMLEVELSSTATUSDELETED  = "Deleted"
	BILLCLAIMLEVELSSTATUSAPPROVED = "Approved"
	BILLCLAIMLEVELSSTATUSREJECTED = "Rejected"
	BILLCLAIMLEVELSSTATUSPENDING  = "Pending"
)
