package constants

//BillClaimLog Constants
const (
	BILLCLAIMLOGSTATUSACTIVE   = "Active"
	BILLCLAIMLOGSTATUSAPPROVED = "Approved"
	BILLCLAIMLOGSTATUSREJECTED = "Rejected"
	BILLCLAIMLOGSTATUSPENDING  = "Pending"
	BILLCLAIMLOGSTATUSDISABLED = "Disabled"
	BILLCLAIMLOGSTATUSDELETED  = "Deleted"
)
