package constants

//DocumentType Constants
const (
	DOCUMENTTYPESTATUSACTIVE   = "Active"
	DOCUMENTTYPESTATUSDISABLED = "Disabled"
	DOCUMENTTYPESTATUSDELETED  = "Deleted"
)

//DocumentScenarios Constants
const (
	DOCUMENTSCENARIOSTATUSACTIVE   = "Active"
	DOCUMENTSCENARIOSTATUSDISABLED = "Disabled"
	DOCUMENTSCENARIOSTATUSDELETED  = "Deleted"
)

//DocumentMuxMaster Constants
const (
	DOCUMENTMUXMASTERSTATUSACTIVE   = "Active"
	DOCUMENTMUXMASTERSTATUSDISABLED = "Disabled"
	DOCUMENTMUXMASTERSTATUSDELETED  = "Deleted"
)

//DocumentPolicy Constants
const (
	DOCUMENTPOLICYSTATUSACTIVE   = "Active"
	DOCUMENTPOLICYSTATUSDISABLED = "Disabled"
	DOCUMENTPOLICYSTATUSDELETED  = "Deleted"
)

//DocumentMaster Constants
const (
	DOCUMENTMASTERSTATUSACTIVE   = "Active"
	DOCUMENTMASTERSTATUSDISABLED = "Disabled"
	DOCUMENTMASTERSTATUSDELETED  = "Deleted"
)

//DocumentPolicyDocuments Constants
const (
	DOCUMENTPOLICYDOCUMENTSSTATUSACTIVE   = "Active"
	DOCUMENTPOLICYDOCUMENTSSTATUSDISABLED = "Disabled"
	DOCUMENTPOLICYDOCUMENTSSTATUSDELETED  = "Deleted"
)
