package constants

// EmployeeLeave Constants
const (
	EMPLOYEELEAVESTATUSACTIVE   = "Active"
	EMPLOYEELEAVESTATUSDISABLED = "Disabled"
	EMPLOYEELEAVESTATUSDELETED  = "Deleted"
)

// EmployeeLeaveLog Constants
const (
	EMPLOYEELEAVELOGSTATUSACTIVE   = "Active"
	EMPLOYEELEAVELOGSTATUSDISABLED = "Disabled"
	EMPLOYEELEAVELOGSTATUSDELETED  = "Deleted"
)
