package constants

//EmployeeJob Constants
const (
	EMPLOYEEJOBSTATUSACTIVE   = "Active"
	EMPLOYEEJOBSTATUSDISABLED = "Disabled"
	EMPLOYEEJOBSTATUSDELETED  = "Deleted"
)

//EmployeeHistory Constants
const (
	EMPLOYEEHISTORYSTATUSACTIVE   = "Active"
	EMPLOYEEHISTORYSTATUSDISABLED = "Disabled"
	EMPLOYEEHISTORYSTATUSDELETED  = "Deleted"
)

//EmergencyCOntact Constants
const (
	EMERGENCYCONTACTSTATUSACTIVE   = "Active"
	EMERGENCYCONTACTSTATUSDISABLED = "Disabled"
	EMERGENCYCONTACTSTATUSDELETED  = "Deleted"
)
