package constants

//Employee Constants
const (
	EMPLOYEEATTENDANCECALENDARSTATUSACTIVE   = "Active"
	EMPLOYEEATTENDANCECALENDARSTATUSDISABLED = "Disabled"
	EMPLOYEEATTENDANCECALENDARSTATUSDELETED  = "Deleted"
)
