package constants

//EmployeeonboardingCheckList Constants
const (
	EMPLOYEEONBOARDINGCHECKLISTSTATUSACTIVE   = "Active"
	EMPLOYEEONBOARDINGCHECKLISTSTATUSDISABLED = "Disabled"
	EMPLOYEEONBOARDINGCHECKLISTSTATUSDELETED  = "Deleted"
)
