package constants

//Employee Constants
const (
	EMPLOYEESTATUSACTIVE             = "Active"
	EMPLOYEESTATUSDISABLED           = "Disabled"
	EMPLOYEESTATUSDELETED            = "Deleted"
	EMPLOYEESTATUSONBORADING         = "Onboarding"
	EMPLOYEESTATUSREJECT             = "Reject"
	EMPLOYEESTATUSPROBATIONARY       = "Probationary"
	EMPLOYEESTATUSACTIVEEMPLOYEE     = "Activeemployee"
	EMPLOYEESTATUSBENCH              = "Bench"
	EMPLOYEESTATUSNOTICE             = "Notice"
	EMPLOYEESTATUSOFFBOARD           = "Offboard"
	EMPLOYEESTATUSRELIEVE            = "Relieve"
	EMPLOYEESTATUSONBORADINGDESC     = "Onboarding started"
	EMPLOYEESTATUSREJECTDESC         = "Rejected"
	EMPLOYEESTATUSPROBATIONARYDESC   = "Probationary started"
	EMPLOYEESTATUSACTIVEEMPLOYEEDESC = "Activeemployee started"
	EMPLOYEESTATUSBENCHDESC          = "Bench started"
	EMPLOYEESTATUSNOTICEDESC         = "Notice started"
	EMPLOYEESTATUSOFFBOARDDECS       = "Offboard started"
	EMPLOYEESTATUSRELIEVEDECS        = "Relieve started"
	EMPLOYEESTATUSCOMPLETEDSTAGE     = "Completed"
	EMPLOYEESTATUSACTIVESTAGE        = "Active"
	EMPLOYEELOPCASEUNPLANNED         = "UnPlanned"
	EMPLOYEELOPCASEPLANNED           = "Planned"
	EMPLOYEELOPCASEPRESENT           = "Present"
	EMPLOYEELOPCASECALCULATE         = "Calculated"
)

//Employee Experience Constants
const (
	EMPLOYEEEXPERIENCESTATUSACTIVE   = "Active"
	EMPLOYEEEXPERIENCESTATUSDISABLED = "Disabled"
	EMPLOYEEEXPERIENCESTATUSDELETED  = "Deleted"
)

//Employee Education Constants
const (
	EMPLOYEEEDUCATIONSTATUSACTIVE   = "Active"
	EMPLOYEEEDUCATIONSTATUSDISABLED = "Disabled"
	EMPLOYEEEDUCATIONSTATUSDELETED  = "Deleted"
)

//Employee Family Members Constants
const (
	EMPLOYEEFAMILYMEMBERSSTATUSACTIVE   = "Active"
	EMPLOYEEFAMILYMEMBERSSTATUSDISABLED = "Disabled"
	EMPLOYEEFAMILYMEMBERSSTATUSDELETED  = "Deleted"
)

//Employee Time Off Constants
const (
	EMPLOYEETIMEOFFSTATUSACTIVE        = "Active"
	EMPLOYEETIMEOFFSTATUSDISABLED      = "Disabled"
	EMPLOYEETIMEOFFSTATUSDELETED       = "Deleted"
	EMPLOYEETIMEOFFSTATUSCANCEL        = "Cancel"
	EMPLOYEETIMEOFFSTATUSREQUEST       = "Request"
	EMPLOYEETIMEOFFSTATUSAPPROVE       = "Approved"
	EMPLOYEETIMEOFFSTATUSREJECT        = "Rejected"
	EMPLOYEETIMEOFFSTATUSREVOKE        = "Revoke"
	EMPLOYEETIMEOFFSTATUSREVOKEREQUEST = "RevokeRequest"
)
const (
	EMPLOYEESALARYSTATUSACTIVE   = "Active"
	EMPLOYEESALARYSTATUSDISABLED = "Disabled"
	EMPLOYEESALARYSTATUSDELETED  = "Deleted"
)
