package constants

//EmployeeOffboardingCheckList Constants
const (
	EMPLOYEEOFFBOARDINGCHECKLISTSTATUSACTIVE   = "Active"
	EMPLOYEEOFFBOARDINGCHECKLISTSTATUSDISABLED = "Disabled"
	EMPLOYEEOFFBOARDINGCHECKLISTSTATUSDELETED  = "Deleted"
)
