package constants

//expenseCategory Constants
const (
	EXPENSECATEGORYSTATUSACTIVE   = "Active"
	EXPENSECATEGORYSTATUSDISABLED = "Disabled"
	EXPENSECATEGORYSTATUSDELETED  = "Deleted"
)

//expenseSubcategory Constants
const (
	EXPENSESUBCATEGORYSTATUSACTIVE   = "Active"
	EXPENSESUBCATEGORYSTATUSDISABLED = "Disabled"
	EXPENSESUBCATEGORYSTATUSDELETED  = "Deleted"
)

//expenseCategoryList Constants
const (
	EXPENSECATEGORYLISTSTATUSACTIVE   = "Active"
	EXPENSECATEGORYLISTSTATUSDISABLED = "Disabled"
	EXPENSECATEGORYLISTSTATUSDELETED  = "Deleted"
)
