package constants

const (
	SMSLOGSTATUSTRUE    = true
	SMSLOGSTATUSFALSE   = false
	SMSLOGSTATUSACTIVE  = "Active"
	SMSLOGSTATUSDISABLE = "Disabled"
	SMSLOGSTATUSDELETED = "Deleted"
)
const (
	EMAILLOGSTATUSTRUE    = true
	EMAILLOGSTATUSFALSE   = false
	EMAILLOGSTATUSACTIVE  = "Active"
	EMAILLOGSTATUSDISABLE = "Disabled"
	EMAILLOGSTATUSDELETED = "Deleted"
)
