package constants

// PayrollPolicyDetectionEarning Constants
const (
	PAYROLLPOLICYDETECTIONSTATUSACTIVE   = "Active"
	PAYROLLPOLICYDETECTIONSTATUSDISABLED = "Disabled"
	PAYROLLPOLICYDETECTIONSTATUSDELETED  = "Deleted"
)
