package constants

// PayrollPolicyEarning Constants
const (
	PAYROLLPOLICYEARNINGSTATUSACTIVE   = "Active"
	PAYROLLPOLICYEARNINGSTATUSDISABLED = "Disabled"
	PAYROLLPOLICYEARNINGSTATUSDELETED  = "Deleted"
)
