package constants

const (
	SALARYCONFIGLOGSTATUSACTIVE   = "Active"
	SALARYCONFIGLOGSTATUSACHIEVED = "Achieved"
	SALARYCONFIGLOGSTATUSDISABLED = "Disabled"
	SALARYCONFIGLOGSTATUSDELETED  = "Deleted"
)
