package constants

//User Constants
const (
	USERSTATUSACTIVE   = "Active"
	USERSTATUSDISABLED = "Disabled"
	USERSTATUSDELETED  = "Deleted"
	USERSTATUSINIT     = "Init"

	USERTYPESTATUSACTIVE   = "Active"
	USERTYPESTATUSDISABLED = "Disabled"
	USERTYPESTATUSDELETED  = "Deleted"
)
const (
	USERTYPEHR         = "HR"
	USERTYPESUPERADMIN = "SuperAdmin"
	USERTYPEADMIN      = "Admin"
)

//Organisation Constants
const (
	ORGANISATIONOWNERSTATUSACTIVE   = "Active"
	ORGANISATIONOWNERSTATUSDISABLED = "Disabled"
	ORGANISATIONOWNERSTATUSDELETED  = "Deleted"
)

//User Location Constants
const (
	USERLOCATIONSTATUSACTIVE       = "Active"
	USERLOCATIONSTATUSDISABLED     = "Disabled"
	USERLOCATIONSTATUSDELETED      = "Deleted"
	USERLOCATIONSTATUSERROR        = "Error"
	USERLOCATIONENTRYSTATUSGENERAL = "General"
)

//user type
const (
	USERTYPEEMPLOYEE = "Employee"
)

//User Location Tracker Constants
const (
	USERLOCATIONTRACKERSTATUSACTIVE   = "Active"
	USERLOCATIONTRACKERSTATUSDISABLED = "Disabled"
	USERLOCATIONTRACKERSTATUSDELETED  = "Deleted"
)
