
[development]
database_name="harit"
mongodb_url="mongodb://localhost:27018,localhost:27019,localhost:27020/?replicaSet=rsSample"
SMS_URL = "http://bulk.smseasy.in/api/mt/SendSMS"
SMS_URL_BKUP = "http://sms.logikoof.com/api/mt/SendSMS"
SMS_USERNAME="urncch"
SMS_PASSWORD="urncch"
SMS_SENDER_ID="URNCCH"
SMS_CHANNEL="Trans"
SMS_DCS=0
SMS_FLASH=0
SMS_ROUTE="1"
#EMAIL_FROM="bpmsdevelopment@gmail.com" 
#EMAIL_FROM_PASSWORD="#nature32"
#EMAIL_SMTPHOST="smtp.gmail.com"
#EMAIL_SMTPPORT="587"

EMAIL_FROM="urncc@logikoof.in" 
EMAIL_FROM_PASSWORD="#nature32"
EMAIL_SMTPHOST="smtp.yandex.com"
EMAIL_SMTPPORT="587"
BASE_URL="http://stage.municipal.com"
API_BASE_URL="http://139.99.21.181:8085/api"
LOGIN_URL="/#/login"
CONTACTUS_URL="/#/contact"
FILE_URL = "C:/solo/repos/harit/files/documents/"
FILE_URL_D = "documents/"
TEMPLATE_URL = "C:/solo/repos/harit/files/templates/"
PUSHNOTIFICATION_CRED = "C:/solo/repos/harit/files/config/haritapp-1dd2a-firebase-adminsdk-p4pj9-8b717a51d5.json"



[development2]
database_name="soilprotectionv2"
mongodb_url="mongodb://localhost:27018,localhost:27019,localhost:27020/?replicaSet=rsSample"
SMS_URL = "http://bulk.smseasy.in/api/mt/SendSMS"
SMS_URL_BKUP = "http://sms.logikoof.com/api/mt/SendSMS"
SMS_USERNAME="urncch"
SMS_PASSWORD="urncch"
SMS_SENDER_ID="URNCCH"
SMS_CHANNEL="Trans"
SMS_DCS=0
SMS_FLASH=0
SMS_ROUTE="1"
#EMAIL_FROM="bpmsdevelopment@gmail.com" 
#EMAIL_FROM_PASSWORD="#nature32"
#EMAIL_SMTPHOST="smtp.gmail.com"
#EMAIL_SMTPPORT="587"

EMAIL_FROM="urncc@logikoof.in" 
EMAIL_FROM_PASSWORD="#nature32"
EMAIL_SMTPHOST="smtp.yandex.com"
EMAIL_SMTPPORT="587"
BASE_URL="http://stage.municipal.com"
API_BASE_URL="http://139.99.21.181:8085/api"
LOGIN_URL="/#/login"
CONTACTUS_URL="/#/contact"
FILE_URL = "C:/solo/repos/harit/files/documents/"
FILE_URL_D = "documents/"
TEMPLATE_URL = "C:/solo/repos/harit/files/templates/"
PUSHNOTIFICATION_CRED = "C:/solo/repos/harit/files/config/haritapp-1dd2a-firebase-adminsdk-p4pj9-8b717a51d5.json"




