[development]
database_name="lgf-ccc"
mongodb_url="mongodb://localhost:27018,localhost:27019,localhost:27020/?replicaSet=rsSample"
SMS_URL = "http://sms.logikoof.com/api/mt/SendSMS"
SMS_USERNAME="logikoof"
SMS_PASSWORD="logikoof" 
SMS_SENDER_ID="LOGIKF"
SMS_CHANNEL="Trans"
SMS_DCS=0
SMS_FLASH=0
SMS_ROUTE="1"
EMAIL_FROM="bpmsdevelopment@gmail.com" 
EMAIL_FROM_PASSWORD="#nature32"
EMAIL_SMTPHOST="smtp.gmail.com"
EMAIL_SMTPPORT="587"
BASE_URL="https://lgfccc.logikoof.com/api"
API_BASE_URL="https://api.lgfccc.logikoof.com"
LOGIN_URL="/#/login"
CONTACTUS_URL="/#/contact"
FILE_URL = "C:/solo/repos/ccc/files/documents/"
FILE_URL_D = "documents/"
TEMPLATE_URL = "templates/"
STRIP_DOC_LOC = "/api/documents/"
DOC_LOC_URL = "/documents/{folder1}/{file}"
PUSHNOTIFICATION_CRED = "C:/solo/repos/lgf-ccc/files/config/lgf-ccc-mobile-app-171a4-firebase-adminsdk-uox9y-e8ccbc1825.json"


[local]
database_name="lgf-ccc"
mongodb_url="mongodb://localhost:27018,localhost:27019,localhost:27020/?replicaSet=rsSample"
SMS_URL = "http://sms.logikoof.com/api/mt/SendSMS"
SMS_USERNAME="logikoof"
SMS_PASSWORD="logikoof"
SMS_SENDER_ID="LOGIKF"
SMS_CHANNEL="Trans"
SMS_DCS=0
SMS_FLASH=0
SMS_ROUTE="1"
EMAIL_FROM="bpmsdevelopment@gmail.com" 
EMAIL_FROM_PASSWORD="#nature32"
EMAIL_SMTPHOST="smtp.gmail.com"
EMAIL_SMTPPORT="587"
BASE_URL="http://municipal.logikoof.in"
API_BASE_URL=" http://api.municipal.logikoof.in"
LOGIN_URL="/#/login"
CONTACTUS_URL="/#/contact"
FILE_URL = "C:/solo/repos/ccc/files/documents/"
FILE_URL_D = "documents/"
TEMPLATE_URL = "templates/"
STRIP_DOC_LOC = "/api/documents/"
DOC_LOC_URL = "/documents/{folder1}/{file}"
PUSHNOTIFICATION_CRED = "C:/solo/repos/lgf-ccc/files/config/lgf-ccc-mobile-app-171a4-firebase-adminsdk-uox9y-e8ccbc1825.json"



[prod]
database_name="lgf-cccprod"
mongodb_url="mongodb://localhost:27018,localhost:27019,localhost:27020/?replicaSet=rsSample"
SMS_URL = "http://sms.logikoof.com/api/mt/SendSMS"
SMS_USERNAME="logikoof"
SMS_PASSWORD="logikoof"
SMS_SENDER_ID="LOGIKF"
SMS_CHANNEL="Trans"
SMS_DCS=0
SMS_FLASH=0
SMS_ROUTE="1"
EMAIL_FROM="bpmsdevelopment@gmail.com" 
EMAIL_FROM_PASSWORD="#nature32"
EMAIL_SMTPHOST="smtp.gmail.com"
EMAIL_SMTPPORT="587"
BASE_URL="https://lgf-ccc.logikoof.com/api"
API_BASE_URL=" http://api.lgf-ccc.logikoof.com"
LOGIN_URL="/#/login"
CONTACTUS_URL="/#/contact"
FILE_URL = "C:/solo/repos/ccc/files/documents/"
FILE_URL_D = "documents/"
TEMPLATE_URL = "templates/"
STRIP_DOC_LOC = "/api/documents/"
DOC_LOC_URL = "/documents/{folder1}/{file}"
PUSHNOTIFICATION_CRED = "C:/solo/repos/lgf-ccc/files/config/lgf-ccc-mobile-app-171a4-firebase-adminsdk-uox9y-e8ccbc1825.json"
