package constants

//ULB Constants
const (
	ULBSTATUSACTIVE            = "Active"
	ULBSTATUSDISABLED          = "Disabled"
	ULBSTATUSDELETED           = "Deleted"
	ULBTESTCERTSTATUSNEW       = "New"
	ULBTESTCERTSTATUSREAPPLIED = "ReApplied"
	ULBTESTCERTSTATUSACTIVE    = "Active"
	ULBTESTCERTSTATUSREJECTED  = "Rejected"
	ULBTESTCERTSTATUSDISABLED  = "Disabled"
	ULBTESTCERTSTATUSDELETED   = "Deleted"
	ULBEXCELTESTCERTREAPPLIED  = "reApplied"
	ULBEXCELTESTCERTAPPROVED   = "approved"
	ULBEXCELTESTCERTREJECTED   = "reject"
	ULBEXCELTESTCERTPENDING    = "pending"
	ULBEXCELTESTCERTEXPIRY     = "expiry"
)
