package constants

//SMS Config
const (
	SMSURL      = "SMS_URL"
	SMSUSERNAME = "SMS_USERNAME"
	SMSPASSWORD = "SMS_PASSWORD"
	SMSSENDERID = "SMS_SENDER_ID"
	SMSCHANNEL  = "SMS_CHANNEL"
	SMSDCS      = "SMS_DCS"
	SMSFLASH    = "SMS_FLASH"
	SMSROUTE    = "SMS_ROUTE"
)
