[development]
database_name="hrms"
mongodb_url="mongodb://localhost:27017"
SMS_URL = "http://sms.logikoof.com/api/mt/SendSMS"
SMS_USERNAME="logikoof"
SMS_PASSWORD="logikoof" 
SMS_SENDER_ID="LOGIKF"
SMS_CHANNEL="Trans"
SMS_DCS=0
SMS_FLASH=0
BASIC=45
HRA=20
CONVEYANCE=1600
EDUCTION=0
PERFORMANCE=20
PF=12
ESIC=1.75
SMS_ROUTE="1"
APK_URL="https://play.google.com/store/apps/details?id=com.lgfhrms"
EMAIL_FROM="noreply.lgf_hrms@logikoof.in" 
EMAIL_FROM_PASSWORD="#nature32"
EMAIL_SMTPHOST="smtp.yandex.com"
EMAIL_SMTPPORT="587"
BASE_URL="https://hrms.logikoof.com/api"
API_BASE_URL="https://api.hrms.logikoof.com"
LOGIN_URL="/#/login"
CONTACTUS_URL="/#/contact"
FILE_URL = "C:/solo/repos/hrms/files/documents/"
FILE_URL_D = "documents/"
TEMPLATE_URL = "C:/solo/repos/hrms/files/documents/templates/"
STRIP_DOC_LOC = "/api/documents/"
DOC_LOC_URL = "/documents/{folder1}/{file}"
PUSHNOTIFICATION_CRED = "C:/solo/repos/hrmsdev/files/config/hrms-mobile-app-171a4-firebase-adminsdk-uox9y-e8ccbc1825.json"


[local]
database_name="hrms"
mongodb_url="mongodb://localhost:27018,localhost:27019,localhost:27020/?replicaSet=rsSample"
SMS_URL = "http://sms.logikoof.com/api/mt/SendSMS"
SMS_USERNAME="logikoof"
SMS_PASSWORD="logikoof"
SMS_SENDER_ID="LOGIKF"
SMS_CHANNEL="Trans"
SMS_DCS=0
SMS_FLASH=0
SMS_ROUTE="1"
EMAIL_FROM="bpmsdevelopment@gmail.com" 
EMAIL_FROM_PASSWORD="#nature32"
EMAIL_SMTPHOST="smtp.gmail.com"
EMAIL_SMTPPORT="587"
BASE_URL="http://municipal.logikoof.in"
API_BASE_URL=" http://api.municipal.logikoof.in"
LOGIN_URL="/#/login"
CONTACTUS_URL="/#/contact"
FILE_URL = "C:/solo/repos/hrms/files/documents/"
FILE_URL_D = "documents/"
TEMPLATE_URL = "templates/"
PUSHNOTIFICATION_CRED = "C:/solo/repos/hrms/files/config/hrms-mobile-app-171a4-firebase-adminsdk-uox9y-e8ccbc1825.json"



[prod]
database_name="hrms"
mongodb_url="mongodb://localhost:27018,localhost:27019,localhost:27020/?replicaSet=rsSample"
SMS_URL = "http://sms.logikoof.com/api/mt/SendSMS"
SMS_USERNAME="logikoof"
SMS_PASSWORD="logikoof"
SMS_SENDER_ID="LOGIKF"
SMS_CHANNEL="Trans"
SMS_DCS=0
SMS_FLASH=0
SMS_ROUTE="1"
BASIC=45
HRA=20
CONVEYANCE=1600
EDUCTION=0
PERFORMANCE=20
PF=12
ESIC=1.75
APK_URL="https://play.google.com/store/apps/details?id=com.lgfhrms"
EMAIL_FROM="solomon@logikoof.in" 
EMAIL_FROM_PASSWORD="#nature32"
EMAIL_SMTPHOST="smtp.yandex.com"
EMAIL_SMTPPORT="587"
BASE_URL="https://hrms.logikoof.org/api"
API_BASE_URL="http://api.hrms.logikoof.org"
LOGIN_URL="/#/login"
CONTACTUS_URL="/#/contact"
FILE_URL = "C:/solo/repos/hrms/files/documents/"
FILE_URL_D = "documents/"
TEMPLATE_URL = "templates/"
STRIP_DOC_LOC = "/api/documents/"
DOC_LOC_URL = "/documents/{folder1}/{file}"
PUSHNOTIFICATION_CRED = "C:/solo/repos/hrms/files/config/hrms-mobile-app-171a4-firebase-adminsdk-uox9y-e8ccbc1825.json"
