package constants

const (
	COLLECTIONCOMMUNICATIONCREDIT    = "communicationcredit"
	COMMUNICATIONCREDITSTATUSTRUE    = true
	COMMUNICATIONCREDITSTATUSFALSE   = false
	COMMUNICATIONCREDITSTATUSACTIVE  = "Active"
	COMMUNICATIONCREDITSTATUSDISABLE = "Disabled"
	COMMUNICATIONCREDITSTATUSDELETED = "Deleted"
	CRIDITTYPESMS                    = "SMS"
	CRIDITTYPEWHATSAPP               = "Whatsapp"
	INSUFFICIENTBALANCE              = "Insufficient Balance"
)
