package constants

//COMMUNICATIONCREDITLOG Constants
const (
	COMMUNICATIONCREDITLOGSTATUSACTIVE   = "Active"
	COMMUNICATIONCREDITLOGSTATUSDISABLED = "Disabled"
	COMMUNICATIONCREDITLOGSTATUSDELETED  = "Deleted"
)
