package constants

const (
	COLLECTIONCONTENT    = "content"
	CONTENTSTATUSACTIVE  = "Active"
	CONTENTSTATUSDISABLE = "Disabled"
	CONTENTSTATUSDELETED = "Deleted"
)
const (
	CONTENTTYPESMS     = "S"
	CONTENTTYPEVOICE   = "V"
	CONTENTTYPEVIDEO   = "U"
	CONTENTTYPEPOSTER  = "P"
	CONTENTTYPEDOCMENT = "D"
)
