package constants

//DEALER Constants
const (
	DEALERSTATUSACTIVE   = "Active"
	DEALERSTATUSDISABLED = "Disabled"
	DEALERSTATUSDELETED  = "Deleted"
	DEALERSTATUSINIT     = "Init"
)
const (
	DEALERCERTIFICATIONSTATUSAPPLY      = "Applied"
	DEALERCERTIFICATIONSTATUSAPPROVED   = "Approved"
	DEALERCERTIFICATIONSTATUSREJECT     = "Rejected"
	DEALERCERTIFICATIONSTATUSINIT       = "Init"
	DEALERCERTIFICATIONSTATUSNOTAPPLIED = "NotApplied"
)
