package constants

const (
	COLLECTIONDISSEMINATION        = "dissemination"
	DISSEMINATIONSTATUSACTIVE      = "Active"
	DISSEMINATIONSTATUSDISABLE     = "Disabled"
	DISSEMINATIONSTATUSDELETED     = "Deleted"
	DISSEMINATIONMODESMS           = "SMS"
	DISSEMINATIONMODEWHATSAPP      = "Whatsapp"
	DISSEMINATIONMODENOTTIFICATION = "Notify"
	DISSEMINATIONMODETELEGRAM      = "Telegram"
)
