package constants

const (
	DISTRICTWEATHERALERTNOTINRANGESTATUSACTIVE  = "Active"
	DISTRICTWEATHERALERTNOTINRANGESTATUSDISABLE = "Disabled"
	DISTRICTWEATHERALERTNOTINRANGESTATUSDELETED = "Deleted"
)
