package constants

const (
	DISTRICTWEATHERALERTDISSIMINATIONSTATUSACTIVE  = "Active"
	DISTRICTWEATHERALERTDISSIMINATIONSTATUSDISABLE = "Disabled"
	DISTRICTWEATHERALERTDISSIMINATIONSTATUSDELETED = "Deleted"
)
