package constants

//FarmerCrop Constants
const (
	COLLECTIONFARMERCROP     = "farmerCrop"
	FARMERCROPSTATUSACTIVE   = "Active"
	FARMERCROPSTATUSDISABLED = "Disabled"
	FARMERCROPSTATUSDELETED  = "Deleted"
	FARMERCROPSTATUSDONE     = "DONE"
	FARMERCROPSTATUSWIP      = "WIP"
)

//FarmerLiveStock Constants
const (
	COLLECTIONFARMERLIVESTOCK     = "farmerLiveStock"
	FARMERLIVESTOCKSTATUSACTIVE   = "Active"
	FARMERLIVESTOCKSTATUSDISABLED = "Disabled"
	FARMERLIVESTOCKSTATUSDELETED  = "Deleted"
)

//FarmerSoilData Constants
const (
	COLLECTIONFARMERSOILDATA     = "farmerSoilData"
	FARMERSOILDATASTATUSACTIVE   = "Active"
	FARMERSOILDATASTATUSDISABLED = "Disabled"
	FARMERSOILDATASTATUSDELETED  = "Deleted"
)

//FarmerCropCalendar Constants
const (
	COLLECTIONFARMERCROPCALENDAR     = "farmerCropCalendar"
	FARMERCROPCALENDARSTATUSACTIVE   = "Active"
	FARMERCROPCALENDARSTATUSDISABLED = "Disabled"
	FARMERCROPCALENDARSTATUSDELETED  = "Deleted"
)
