package constants

//LANDCrop Constants
const (
	COLLECTIONLANDCROP     = "landCrop"
	LANDCROPSTATUSACTIVE   = "Active"
	LANDCROPSTATUSDISABLED = "Disabled"
	LANDCROPSTATUSDELETED  = "Deleted"
	LANDCROPSTATUSDONE     = "DONE"
	LANDCROPSTATUSWIP      = "WIP"
)

const (
	COLLECTIONLANDCROPCALENDARITEM     = "landCropCalendarItem"
	LANDCROPCALENDARITEMSTATUSACTIVE   = "Active"
	LANDCROPCALENDARITEMSTATUSDISABLED = "Disabled"
	LANDCROPCALENDARITEMSTATUSDELETED  = "Deleted"
)
