package constants

//ORDER Constants
const (
	ORDERSTATUSACTIVE    = "Active"
	ORDERSTATUSDISABLED  = "Disabled"
	ORDERSTATUSDELETED   = "Deleted"
	ORDERSTATUSINIT      = "Init"
	ORDERSTATUSCOMPLETED = "Completed"
	ORDERSTATUSPENDING   = "Pending"
)
const (
	DEALER = "D"
	FARMER = "F"
)
const (
	ORDERPAYMENTSTATUSACTIVE    = "Active"
	ORDERPAYMENTSTATUSDISABLED  = "Disabled"
	ORDERPAYMENTSTATUSDELETED   = "Deleted"
	ORDERPAYMENTSTATUSINIT      = "Init"
	ORDERPAYMENTSTATUSCOMPLETED = "Completed"
	ORDERPAYMENTSTATUSPENDING   = "Pending"
)
