package constants

//QUERY Constants
const (
	QUERYSTATUSACTIVE   = "Active"
	QUERYSTATUSDISABLED = "Disabled"
	QUERYSTATUSDELETED  = "Deleted"
	QUERYSTATUSCREATED  = "C"
	QUERYSTATUSRESOLVED = "R"
	QUERYSTATUSASSIGN   = "O"
	QUERYSTATUSMODIFY   = "M"
)
