package constants

const (
	COLLECTIONSMSLOG    = "smslog"
	SMSLOGSTATUSTRUE    = true
	SMSLOGSTATUSFALSE   = false
	SMSLOGSTATUSACTIVE  = "Active"
	SMSLOGSTATUSDISABLE = "Disabled"
	SMSLOGSTATUSDELETED = "Deleted"
)
const (
	COLLECTIONWHATSAPPLOG    = "whatsapplog"
	WHATSAPPLOGSTATUSTRUE    = true
	WHATSAPPLOGSTATUSFALSE   = false
	WHATSAPPLOGSTATUSACTIVE  = "Active"
	WHATSAPPLOGSTATUSDISABLE = "Disabled"
	WHATSAPPLOGSTATUSDELETED = "Deleted"
)
const (
	COLLECTIONWHATSAPPTEMPLATE = "whatsapptemplate"
)
const (
	COLLECTIONTELEGRAMLOG    = "telegramlog"
	TELEGRAMLOGSTATUSTRUE    = true
	TELEGRAMLOGSTATUSFALSE   = false
	TELEGRAMLOGSTATUSACTIVE  = "Active"
	TELEGRAMLOGSTATUSDISABLE = "Disabled"
	TELEGRAMLOGSTATUSDELETED = "Deleted"
)
const (
	COLLECTIONEMAILLOG    = "emaillog"
	EMAILLOGSTATUSTRUE    = true
	EMAILLOGSTATUSFALSE   = false
	EMAILLOGSTATUSACTIVE  = "Active"
	EMAILLOGSTATUSDISABLE = "Disabled"
	EMAILLOGSTATUSDELETED = "Deleted"
)

const (
	COLLECTIONNOTIFICATIONLOG    = "notificationlog"
	NOTIFICATIONLOGSTATUSTRUE    = true
	NOTIFICATIONLOGSTATUSFALSE   = false
	NOTIFICATIONLOGSTATUSACTIVE  = "Active"
	NOTIFICATIONLOGSTATUSDISABLE = "Disabled"
	NOTIFICATIONLOGSTATUSDELETED = "Deleted"
)
