package constants

const (
	STATEWEATHERALERTDISSIMINATIONSTATUSACTIVE  = "Active"
	STATEWEATHERALERTDISSIMINATIONSTATUSDISABLE = "Disabled"
	STATEWEATHERALERTDISSIMINATIONSTATUSDELETED = "Deleted"
)
