package constants

//SUBCATEGORY Constants
const (
	SUBCATEGORYSTATUSACTIVE   = "Active"
	SUBCATEGORYSTATUSDISABLED = "Disabled"
	SUBCATEGORYSTATUSDELETED  = "Deleted"
	SUBCATEGORYSTATUSINIT     = "Init"
)
