package constants

const (
	USERLOGINLOGSTATUSLOGIN   = "Login"
	USERLOGINLOGSTATUSLOGOUT  = "Logout"
	USERLOGINLOGSTATUSACTIVE  = "Active"
	USERLOGINLOGSTATUSDISABLE = "Disabled"
	USERLOGINLOGSTATUSDELETED = "Deleted"
)
