package constants

const (
	WALLETSTATUSACTIVE   = "Active"
	WALLETSTATUSDISABLED = "Disabled"
	WALLETSTATUSDELETED  = "Deleted"

	WALLETLOGSTATUSACTIVE   = "Active"
	WALLETLOGSTATUSDISABLED = "Disabled"
	WALLETLOGSTATUSDELETED  = "Deleted"
)
